project:
  type: website
  output-dir: docs

website:
  title: "Berkant AYTEMIR's Analytics Lab"
  navbar:
    background: '#111111'
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/berkantaytemir
      - icon: instagram
        href: https://www.instagram.com/aytemirberkant/
      - icon: linkedin
        href: https://www.linkedin.com/in/berkant-aytemir-8798111ba/

  sidebar:
    - title: "Assignments"
      navbar:
        background: transparent
    
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2023" 
    border: true
format:
  html:
    mainfont : arial
    fontcolor: "#FFFCFC"
    linkcolor: "#F49F9F"
    toc: true
    toc-location: left
    theme: 
      light: darkly
      dark: darkly
    css: styles.css


editor: visual

