<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Berkant AYTEMIR’s Analytics Lab - Assignment 2- Web Scraping of Turkish Movies from IMDb</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assignments/assignment-1.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Berkant AYTEMIR’s Analytics Lab</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../posts.html" rel="" target="">
 <span class="menu-text">My Posts</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-emu430-coursework" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">EMU430 Coursework</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-emu430-coursework">    
        <li>
    <a class="dropdown-item" href="../assignments.html" rel="" target="">
 <span class="dropdown-text">Assignments</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../project.html" rel="" target="">
 <span class="dropdown-text">Project</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto tools-wide">
    <a href="https://github.com/berkantaytemir" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <a href="https://www.instagram.com/aytemirberkant/" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-instagram"></i></a>
    <a href="https://www.linkedin.com/in/berkant-aytemir-8798111ba/" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-linkedin"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../assignments/assignment-2.html">Assignment 2- Web Scraping of Turkish Movies from IMDb</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">My Assignments</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/assignment-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/assignment-2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Assignment 2- Web Scraping of Turkish Movies from IMDb</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#web-scraping-of-turkish-movies-from-imdb" id="toc-web-scraping-of-turkish-movies-from-imdb" class="nav-link active" data-scroll-target="#web-scraping-of-turkish-movies-from-imdb">Web Scraping of Turkish Movies from IMDb</a>
  <ul class="collapse">
  <li><a href="#question-1." id="toc-question-1." class="nav-link" data-scroll-target="#question-1.">Question 1.</a></li>
  <li><a href="#question-2." id="toc-question-2." class="nav-link" data-scroll-target="#question-2.">Question 2.</a></li>
  <li><a href="#question-3." id="toc-question-3." class="nav-link" data-scroll-target="#question-3.">Question 3.</a>
  <ul class="collapse">
  <li><a href="#a" id="toc-a" class="nav-link" data-scroll-target="#a">3.a</a></li>
  <li><a href="#b" id="toc-b" class="nav-link" data-scroll-target="#b">3.b</a></li>
  <li><a href="#c" id="toc-c" class="nav-link" data-scroll-target="#c">3.c</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  </ul></li>
  <li><a href="#question-4." id="toc-question-4." class="nav-link" data-scroll-target="#question-4.">Question 4.</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 2- Web Scraping of Turkish Movies from IMDb</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="web-scraping-of-turkish-movies-from-imdb" class="level1">
<h1>Web Scraping of Turkish Movies from IMDb</h1>
<p>Before I move on to code explanation part , I want to indicate that there is an additional movie that has been added to IMDB list . So the data set should be 470 not 469 :)</p>
<section id="question-1." class="level2">
<h2 class="anchored" data-anchor-id="question-1.">Question 1.</h2>
<p>Using the filters on https://m.imdb.com/search, list all Turkish movies with more than 2500 reviews, and save the URLs.</p>
<p>Ans: Do not forget to read the libraries !</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># for everything :)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forcats' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rvest) <span class="co"># for HTML scraping</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'rvest' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'rvest'

The following object is masked from 'package:readr':

    guess_encoding</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>data_pages <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"https://m.imdb.com/search/title/?title_type=feature&amp;release_date=1900-12-31,2009-12-31&amp;num_votes=2500,2147483647&amp;country_of_origin=TR&amp;count=250"</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"https://m.imdb.com/search/title/?title_type=feature&amp;release_date=2010-01-01,2023-12-31&amp;num_votes=2500,2147483647&amp;country_of_origin=TR&amp;count=250"</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>all_title_names <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>all_years <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>all_durations <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>all_ratings <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>all_votes <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (data <span class="cf">in</span> data_pages) {</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  page <span class="ot">&lt;-</span> <span class="fu">read_html</span>(data)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>  title_names <span class="ot">&lt;-</span> page <span class="sc">%&gt;%</span> <span class="fu">html_nodes</span>(<span class="st">'.ipc-title__text'</span>) <span class="sc">%&gt;%</span> <span class="fu">html_text</span>()</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  all_title_names[[<span class="fu">length</span>(all_title_names) <span class="sc">+</span> <span class="dv">1</span>]] <span class="ot">&lt;-</span> title_names</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>  Year <span class="ot">&lt;-</span> page <span class="sc">%&gt;%</span> <span class="fu">html_nodes</span>(<span class="st">".sc-43986a27-7.dBkaPT.dli-title-metadata"</span>) <span class="sc">%&gt;%</span> <span class="fu">html_text</span>()</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  all_years[[<span class="fu">length</span>(all_years) <span class="sc">+</span> <span class="dv">1</span>]] <span class="ot">&lt;-</span> Year</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>  Durations <span class="ot">&lt;-</span> page <span class="sc">%&gt;%</span> <span class="fu">html_nodes</span>(<span class="st">".dli-title-metadata-item:nth-child(2)"</span>) <span class="sc">%&gt;%</span> <span class="fu">html_text</span>()</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>  all_durations[[<span class="fu">length</span>(all_durations) <span class="sc">+</span> <span class="dv">1</span>]] <span class="ot">&lt;-</span> Durations</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>  Ratings <span class="ot">&lt;-</span> page <span class="sc">%&gt;%</span> <span class="fu">html_nodes</span>(<span class="st">".ratingGroup--imdb-rating"</span>) <span class="sc">%&gt;%</span> <span class="fu">html_text</span>()</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>  all_ratings[[<span class="fu">length</span>(all_ratings) <span class="sc">+</span> <span class="dv">1</span>]] <span class="ot">&lt;-</span> Ratings</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>  Votes <span class="ot">&lt;-</span> page <span class="sc">%&gt;%</span> <span class="fu">html_nodes</span>(<span class="st">".kRnqtn"</span>) <span class="sc">%&gt;%</span> <span class="fu">html_text</span>()</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>  all_votes[[<span class="fu">length</span>(all_votes) <span class="sc">+</span> <span class="dv">1</span>]] <span class="ot">&lt;-</span> Votes</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>df_title_names <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">title_names =</span> <span class="fu">unlist</span>(all_title_names))</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>df_years <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Year =</span> <span class="fu">unlist</span>(all_years))</span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a>df_durations <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Durations =</span> <span class="fu">unlist</span>(all_durations))</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a>df_ratings <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Ratings =</span> <span class="fu">unlist</span>(all_ratings))</span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>df_votes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Votes =</span> <span class="fu">unlist</span>(all_votes))</span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a>df_title_names</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                          title_names
1                                     Advanced search
2                            1. Nefes: Vatan Sagolsun
3                                   2. Babam ve Oglum
4                                        3. Masumiyet
5                                            4. Kader
6                                             5. Uzak
7                                           6. Eskiya
8                                          7. A.R.O.G
9                                    8. Sevmek Zamani
10                                  9. Hababam Sinifi
11                                      10. Üç Maymun
12                                          11. Barda
13                                       12. G.O.R.A.
14                                       13. Kabadayi
15                                          14. Yazgi
16                                     15. Issiz Adam
17                           16. Kurtlar Vadisi: Irak
18                                            17. Yol
19                                     18. Yahsi Bati
20                                          19. D@bbe
21                                       20. Iklimler
22                                      21. Vizontele
23                       22. Her Sey Çok Güzel Olacak
24                                         23. Pardon
25                          24. Dünyayi Kurtaran Adam
26                                     25. Tosun Pasa
27                                  26. Bekleme Odasi
28                                     27. Agir Roman
29                               28. Tabutta Rövasata
30                                 29. Organize Isler
31                                         30. Gemide
32                       31. Selvi Boylum Al Yazmalim
33                                         32. Itiraf
34                  33. Dünyayi Kurtaran Adam'in Oglu
35                                   34. Üçüncü Sayfa
36                               35. Neredesin Firuze
37                               36. Saban Oglu Saban
38                                37. Mayis Sikintisi
39                 38. Deli Yürek: Bumerang Cehennemi
40                                      39. Kolpaçino
41                                      40. Susuz Yaz
42                                   41. Recep Ivedik
43                                   42. Günesin Oglu
44                                         43. Kasaba
45                                        44. D@bbe 2
46                                          45. Sinav
47                                  46. Günesi Gördüm
48                                 47. Çöpçüler Krali
49                                        48. Yumurta
50                                49. Baska Dilde Ask
51                                      50. Kiskanmak
52     51. Muro: Nalet Olsun Içimdeki Insan Sevgisine
53                                         52. Vavien
54                                 53. Recep Ivedik 2
55                                         54. C Blok
56                                   55. Gönül Yarasi
57                         56. Kurtlar Vadisi: Gladio
58                                  57. Aaahh Belinda
59                                       58. Hokkabaz
60                                     59. Zügürt Aga
61                                       60. Sonbahar
62                                     61. Üç Kagitçi
63                                     62. Muhsin Bey
64                                 63. Anlat Istanbul
65                                          64. Duvar
66                                65. Merakli Köfteci
67                                         66. Salako
68                               67. Çarikli Milyoner
69               68. Karpuz Kabugundan Gemiler Yapmak
70                                  69. Neseli Günler
71                                  70. Anayurt Oteli
72                                          71. Zübük
73                                         72. Kosmos
74                                  73. Süt Kardesler
75                                            74. 120
76                                    75. Kibar Feyzo
77                                           76. Sürü
78                                            77. Gen
79                                78. 7 Kocali Hürmüz
80                                   79. Kahpe Bizans
81                                 80. En Büyük Saban
82                                     81. Propaganda
83                                       82. Mutluluk
84                                    83. Gölge Oyunu
85                                  84. Tatar Ramazan
86                                    85. Beynelmilel
87                                 86. Çilgin Dersane
88                                      87. Yazi Tura
89                               88. Devrim Arabalari
90                   89. Hababam Sinifi Sinifta Kaldi
91                                   90. Tatli Dillim
92                                 91. Vesikali Yarim
93                                92. Kutsal Damacana
94                                  93. Sari Mercedes
95                                   94. Egreti Gelin
96                                 95. Canim Kardesim
97                    96. Dar Alanda Kisa Paslasmalar
98                        97. Mustafa Hakkinda Hersey
99                                       98. Musallat
100                                   99. Güz Sancisi
101                                100. Küçük Kiyamet
102             101. Hacivat Karagöz Neden Öldürüldü?
103                                  102. Beyaz Melek
104                                         103. Umut
105                        104. Uçurtmayi Vurmasinlar
106                              105. Vizontele Tuuba
107                              106. Korkusuz Korkak
108                                    107. Ah Nerede
109                                      108. Tokatçi
110              109. Maskeli Besler: Intikam Pesinde
111                   110. Azize: Bir Laleli Hikayesi
112                                          111. Süt
113                                 112. Neseli Hayat
114                       113. Hababam Sinifi Tatilde
115                                       114. Insaat
116                                      115. Arabesk
117                          116. Köyden Indim Sehire
118                117. Istanbul Kanatlarimin Altinda
119                                  118. Aile Serefi
120                         119. Maskeli Besler: Irak
121                                      120. Mustafa
122          121. Ask Filmlerinin Unutulmaz Yönetmeni
123                    122. Turist Ömer Uzay Yolu'nda
124                                         123. Okul
125                                  124. Mavi Boncuk
126                                  125. Banker Bilo
127                                         126. Büyü
128                                    127. Bes Vakit
129                                        128. Semum
130                   129. Keloglan Karaprens'e Karsi
131                              130. Çiplak Vatandas
132                               131. O... Çocuklari
133                      132. Hababam Sinifi Uyaniyor
134                                  133. Çiçek Abbas
135                              134. Kapicilar Krali
136                                 135. Gülen Gözler
137                                    136. Hayat Var
138                           137. Pandora'nin Kutusu
139                                        138. Polis
140                      139. Hababam Sinifi Üç Buçuk
141                                       140. Yoksul
142                       141. Son Osmanli Yandim Ali
143                                   142. Bizim Aile
144                                  143. Kanli Nigar
145                                 144. 11'e 10 Kala
146                               145. Doktor Civanim
147                           146. Davaro: Son Eskiya
148                                 147. Kaç Para Kaç
149                                         148. Vali
150                             149. Dondurmam Gaymak
151                              150. Yedi Bela Hüsnü
152                     151. Hababam Sinifi Güle Güle
153                                  152. Devlet Kusu
154                                   153. Gülen Adam
155                                      154. Fasulye
156                              155. Korkuyorum Anne
157                                156. Düttürü Dünya
158                          157. Beyza'nin Kadinlari
159                                         158. Araf
160                       159. Hababam Sinifi Askerde
161                          160. Osmanli Cumhuriyeti
162                                     161. Ögretmen
163                             162. Deli Deli Küpeli
164                                       163. Davaci
165                                       164. Sultan
166                                        165. Garip
167                                  166. Sakar Sakir
168                               167. Salak Milyoner
169                       168. Hababam Sinifi Merhaba
170                                169. Koltuk Belasi
171                                170. Salvar Davasi
172                              171. Filler ve Çimen
173                                172. Ask Tutulmasi
174                                173. O Simdi Asker
175                                     174. Sabaniye
176                          175. Sans Kapiyi Kirinca
177                                     176. Varyemez
178               177. Hababam Sinifi Dokuz Doguruyor
179                                      178. Kilibik
180                         179. On the Way to School
181                                    180. Sekerpare
182                                181. Sosyete Saban
183                                   182. Inek Saban
184                            183. Yüz Numarali Adam
185                                      184. Postaci
186                                        185. Hanzo
187                                      186. Namuslu
188                                       187. Kiraci
189                              188. Ortadirek Saban
190                            189. Katma Deger Saban
191                              190. Ne Olacak Simdi
192                                         191. Ulak
193                            192. Köseyi Dönen Adam
194                                 193. Gerzek Saban
195                  194. Son Ders: Ask ve Üniversite
196                     195. Emret Komutanim: Sah Mat
197                               196. Komser Sekspir
198                                   197. Talih Kusu
199                                 198. Tarzan Rifki
200                                    199. Gol Krali
201                                 200. Saskin Damat
202                                  201. Avanak Apti
203                                    202. Milyarder
204                                     203. Oh Olsun
205                                  204. Hirsiz Var!
206                                    205. Japon Isi
207                             206. Selamsiz Bandosu
208                               207. Gurbetçi Saban
209                           208. Saban Pabucu Yarim
210                                209. Dolap Beygiri
211                               210. Sahte Kabadayi
212                               211. Bekçiler Krali
213                               212. Atla Gel Saban
214                                 213. Uzak Ihtimal
215                               214. Umudumuz Saban
216                       215. Maskeli Besler: Kibris
217                      216. Erkek Güzeli Sefil Bilo
218                                 217. Sark Bülbülü
219                          218. Dokunmayin Sabanima
220                                219. Sen Dul Saban
221                              220. Iyi Aile Çocugu
222                               221. Kanal-i-zasyon
223                             222. Ibo ile Güllüsah
224                                   Recently viewed
225                                   Advanced search
226                              1. Kuru Otlar Üstüne
227                        2. Istanbul Için Son Çagri
228                       3. Yedinci Kogustaki Mucize
229                                 4. Ölümlü Dünya 2
230                                         5. Bihter
231                                   6. Ölümlü Dünya
232                                     7. Kis Uykusu
233                                         8. Dag II
234                                 9. Do Not Disturb
235                     10. Ayla: The Daughter of War
236                                  11. Kurak Günler
237                                   12. Ahlat Agaci
238                       13. Bir Zamanlar Anadolu'da
239                           14. Dabbe: Cin Çarpmasi
240                                        15. Baskin
241                                          16. Kedi
242                                   17. Sen Inandir
243                                        18. Mucize
244                                    19. Fort Bliss
245                                        20. Bergen
246                                     21. Boga Boga
247                                           22. Dag
248                            23. Iyi Adamin 10 Günü
249                                  24. Cinayet Süsü
250                                    25. Fetih 1453
251                        26. The Ottoman Lieutenant
252                                      27. Limonata
253                              28. Illegal Hayatlar
254                                 29. Mucize 2: Ask
255                          30. Kötü Kedi Serafettin
256                                 31. Aaahh Belinda
257                                        32. Siccîn
258                                33. Ask Taktikleri
259                                      34. Can Feda
260                        35. Insanlar Ikiye Ayrilir
261                                      36. Tereddüt
262                                       37. Yeralti
263                         38. D@bbe: Bir Cin Vakasi
264                        39. CM101MMXI Fundamentals
265                                 40. Aile Arasinda
266                             41. Kagittan Hayatlar
267                              42. Kelebegin Rüyasi
268                           43. Bizim Için Sampiyon
269                                    44. Sadece Sen
270                                          45. Cici
271                               46. Ikimizin Yerine
272                47. Cep Herkülü: Naim Süleymanoglu
273                            48. Kaybedenler Kulübü
274                                      49. Sarmasik
275                                50. Yilbasi Gecesi
276                                       51. Bulanti
277                 52. Organize Isler: Sazan Sarmali
278                                 53. Bursa Bülbülü
279                             54. Dabbe: Zehr-i Cin
280                                          55. Daha
281                                    56. Av Mevsimi
282                                    57. Kelebekler
283                                    58. Kar ve Ayi
284                                     59. Geçen Yaz
285                      60. Sen Aydinlatirsin Geceyi
286                                        61. Müslüm
287                                  62. Aykut Eniste
288                                  63. Incir Reçeli
289                             64. Unutursam Fisilda
290                                65. Recep Ivedik 7
291                                   66. Pek Yakinda
292                                       67. Delibal
293                                    68. Nuh Tepesi
294                         69. Kurtlar Vadisi: Vatan
295                                  70. Dügün Dernek
296                                    71. Su ve Ates
297                                       72. Azizler
298                                  73. Biz Böyleyiz
299                                      74. Siccin 2
300                                      75. Panzehir
301                                   76. Okul tirasi
302                                77. Hedefim Sensin
303                               78. Mutluluk Zamani
304                             79. Bir Ask Iki Hayat
305                               80. Celal ile Ceren
306                                       81. Deliler
307                              82. Sen Yasamaya Bak
308                                  83. Cingöz Recai
309                                84. Babamin Kemani
310                                85. Aci Tatli Eksi
311                    86. Enes Batur Gerçek Kahraman
312                                     87. Sag Salim
313                88. Behzat Ç.: Seni Kalbime Gömdüm
314                         89. Ask Tesadüfleri Sever
315                                        90. Çiçero
316                                91. Annemin Yarasi
317                                 92. Kiz Kardesler
318                             93. Senden Bana Kalan
319                             94. Ise Yarar Bir Sey
320                        95. New York'ta Bes Minare
321                              96. Kolpaçino: Bomba
322                                           97. Kin
323                      98. Kaybedenler Kulübü Yolda
324                                 99. Dabbe (Dab6e)
325                       100. Dügün Dernek 2: Sünnet
326               101. Cumali Ceber: Allah Seni Alsin
327                               102. Aykut Eniste 2
328                                        103. Sibel
329                               104. Kardesim Benim
330                   105. Karakomik Filmler: Kaçamak
331                              106. Asiklar Bayrami
332                                 107. Itirazim Var
333                             108. Eltilerin Savasi
334                                 109. Benim Dünyam
335                                110. Hadi Be Oglum
336                      111. Karakomik Filmler: Deli
337                                  112. Küçük Esnaf
338               113. Sen Hiç Ates Böcegi Gördün Mü?
339                                   114. Arif V 216
340                          115. Kolonya Cumhuriyeti
341                            116. Cebimdeki Yabanci
342                            117. Dedemin Insanlari
343                                118. Yol Arkadasim
344                      119. Bi Küçük Eylül Meselesi
345                                      120. Görümce
346                   121. Sen Kiminle Dans Ediyorsun
347            122. Fakat Müzeyyen Bu Derin Bir Tutku
348                     123. Behzat Ç. Ankara Yaniyor
349                                 124. Tamam miyiz?
350                               125. Iftarlik Gazoz
351                                 126. 9 Kere Leyla
352               127. Enes Batur Hayal mi Gerçek mi?
353                                        128. Selam
354                                 129. Beni Çok Sev
355                          130. Zaman Makinesi 1973
356                           131. Istanbul Kirmizisi
357              132. Bizans Oyunlari: Geym of Bizans
358                                  133. Evim Sensin
359                                 134. Eksi Elmalar
360                    135. Karakomik Filmler: Emanet
361                                     136. Iyi Oyun
362                  137. Çok Filim Hareketler Bunlar
363                             138. Yarina Tek Bilet
364                                139. Hükümet Kadin
365                            140. Çakallarla Dans 6
366                   141. Karakomik Filmler: 2 Arada
367                               142. Recep Ivedik 3
368                                  143. Vay Arkadas
369                            144. Sevimli Tehlikeli
370                                  145. Baba Parasi
371                              146. Bayi Toplantisi
372                            147. Kocan Kadar Konus
373                                     148. Deli Ask
374                       149. Hababam Sinifi Yeniden
375                                         150. Reis
376                              151. Ask Sana Benzer
377                                         152. Veda
378                      153. Ask Tesadüfleri Sever 2
379                            154. Türk Isi Dondurma
380                        155. Ali Baba ve 7 Cüceler
381                                       156. Abluka
382                               157. Incir Reçeli 2
383                                         158. Börü
384                          159. Siccîn 3: Cürmü Ask
385                               160. Recep Ivedik 4
386                           161. Bana Masal Anlatma
387                               162. Bir Baba Hindu
388                               163. Eyyvah Eyvah 3
389                                164. Kaçma Birader
390                             165. Gözetleme Kulesi
391                           166. Kurtulus Son Durak
392                               167. Recep Ivedik 6
393                     168. Kutsal Damacana 2: Itmen
394                                  169. Çalgi Çengi
395                         170. Çanakkale Yolun Sonu
396                                     171. Deliha 2
397                              172. Çakallarla Dans
398                             173. Yolun Açik Olsun
399                      174. Sag Salim 2: Sil Bastan
400             175. Çakallarla Dans 3: Sifir Sikinti
401                                          176. Bal
402                                  177. Uzun Hikâye
403                       178. Selam: Bahara Yolculuk
404                               179. Eyyvah Eyvah 2
405                                    180. Kara Bela
406                                181. Sofra Sirlari
407                                     182. Çogunluk
408                    183. Sümela'nin Sifresi: Temel
409                              184. Hükümet Kadin 2
410                                 185. Ejder Kapani
411                                     186. Ya Sonra
412                             187. Ailecek Saskiniz
413                                   188. Kötü Çocuk
414                               189. Cumali Ceber 2
415                                   190. Yol Ayrimi
416                                   191. Sonsuz Ask
417                               192. Recep Ivedik 5
418                                193. Tatlim Tatlim
419                          194. Güzelligin Portresi
420                                       195. Kayhan
421                              196. Kafalar Karisik
422                                 197. Tepenin Ardi
423            198. Romantik Komedi 2: Bekarliga Veda
424                                        199. Müjde
425                                 200. Dedemin Fisi
426                              201. Osman Pazarlama
427                                 202. Bizim Hikaye
428                                  203. Sen Kimsin?
429                     204. Kurtlar Vadisi: Filistin
430                           205. Anadolu Kartallari
431                           206. Kolpaçino 3. Devre
432                                    207. Yok Artik
433             208. Hür Adam: Bediüzzaman Said Nursi
434                             209. G.D.O. Kara Kedi
435                                    210. Ay Lav Yu
436                              211. Yol Arkadasim 2
437                                       212. Deliha
438                                 213. Eyyvah Eyvah
439 214. Celal Tan ve Ailesinin Asiri Acikli Hikayesi
440                                 215. Ali Kundilli
441                               216. Berlin Kaplani
442                                  217. Sabit Kanca
443                                  218. Gise Memuru
444                            219. Çakallarla Dans 4
445                                 220. Olanlar Oldu
446                   221. Kocan Kadar Konus: Dirilis
447                            222. Birlesen Gönüller
448                                 223. Zenne Dancer
449                                  224. OHA Diyorum
450                                    225. Borç Harç
451                             226. Mandira Filozofu
452                                 227. Nadide Hayat
453                            228. Çakallarla Dans 5
454                                 229. Yozgat Blues
455                                 230. Bizi Hatirla
456                        231. Sen Benim HerSeyimsin
457                   232. Bizim Büyük Çaresizligimiz
458                     233. Patron Mutlu Son Istiyor
459                      234. Entelköy Efeköy'e Karsi
460                          235. Niyazi Gül Dörtnala
461                                 236. Içimdeki Ses
462                                237. Hadi Insallah
463                           238. Çalgi Çengi Ikimiz
464                              239. Romantik Komedi
465           240. Çakallarla Dans 2: Hastasiyiz Dede
466                                        241. Açela
467                               242. Kod Adi K.O.Z.
468                           243. Resistance Is Life
469                             244. Alamet-i Kiyamet
470                            245. 15/07 Safak Vakti
471                               246. Deniz ve Günes
472                247. Sihirbazlik Okulunda Bir Türk
473                           248. Guardian of Angels
474                                   Recently viewed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df_years</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Year
1          20092h 8m13+
2           20051h 48mG
3         19971h 50m13+
4         20061h 43m18+
5         20021h 50m18+
6           19962h 8m7+
7          20082h 7m13+
8            19651h 26m
9         19751h 27m18+
10  20081h 49mNot Rated
11        20071h 32m13+
12         20042h 7m18+
13         20072h 20m7+
14           20011h 59m
15        20081h 53m13+
16          20062h 2m7+
17         19821h 47mPG
18         20091h 52m7+
19           20061h 50m
20    20061h 37mUnrated
21        20011h 50m16+
22         19981h 47m7+
23           20051h 39m
24           19821h 31m
25           19761h 30m
26           20031h 32m
27            19972h13+
28           19961h 15m
29        20051h 46m18+
30           19981h 42m
31           19771h 30m
32           20011h 40m
33  20061h 50mNot Rated
34        19991h 32m15+
35   20042h 8mNot Rated
36           19771h 30m
37          19992h 10mG
38            20012h 3m
39        20091h 38m13+
40  19631h 30mNot Rated
41        20081h 30m13+
42           20081h 29m
43           19971h 25m
44           20091h 25m
45      20062hNot Rated
46              20092hG
47        19771h 20m13+
48           20071h 37m
49          20091h 38mG
50           20091h 36m
51          20081h 30mG
52         20091h 40m7+
53        20091h 47m16+
54           19941h 32m
55           20052h 22m
56         20091h 37m7+
57           19861h 40m
58           20062h 2mG
59        19851h 41m13+
60          20081h 39mG
61           19811h 28m
62           19871h 59m
63           20051h 39m
64  19831h 57mNot Rated
65           19761h 15m
66           19741h 27m
67           19831h 26m
68           20041h 37m
69          19781h 35mG
70          19871h 41mG
71           19801h 28m
72         20092h 2m13A
73         19761h 20m7+
74           20081h 54m
75           19781h 23m
76  19781h 57mNot Rated
77           20061h 45m
78            20092h 2m
79           19991h 37m
80           19841h 33m
81               19992h
82           20071h 45m
83           19931h 43m
84           19901h 35m
85           20061h 46m
86           20071h 40m
87           20041h 42m
88             20082h7+
89           19751h 35m
90           19721h 34m
91           19681h 29m
92           20071h 45m
93           19931h 30m
94        20051h 55m13+
95           19731h 25m
96               20002h
97           20041h 59m
98           20071h 35m
99           20091h 52m
100          20061h 30m
101          20062h 15m
102       20071h 55m13A
103 19701h 40mNot Rated
104          19891h 25m
105         20031h 51mG
106          19791h 17m
107          19751h 30m
108          19831h 23m
109          20051h 29m
110          19991h 25m
111         20081h 42mG
112          20091h 40m
113          19771h 37m
114        20031h 53m7+
115        19891h 32m7+
116          19741h 31m
117          19961h 59m
118          19761h 35m
119          20071h 44m
120          20082h 10m
121          19901h 46m
122          19731h 12m
123          20041h 40m
124          19751h 16m
125          19801h 25m
126          20041h 35m
127 20061h 51mNot Rated
128          20081h 56m
129          20061h 45m
130          19851h 14m
131            20082h7+
132          19761h 34m
133          19821h 27m
134          19761h 24m
135          19771h 37m
136  20082h 1mNot Rated
137         20081h 52mG
138          20071h 53m
139          20051h 38m
140          19861h 17m
141           20072h 6m
142          19751h 32m
143          19811h 21m
144 20091h 50mNot Rated
145          19831h 27m
146          19811h 34m
147          19991h 40m
148          20091h 33m
149        20061h 40m7+
150          19831h 24m
151          19811h 21m
152          19801h 19m
153          19901h 31m
154          20001h 45m
155           20042h 8m
156          19881h 31m
157          20062h 17m
158 20061h 37mNot Rated
159          20051h 52m
160          20081h 40m
161          19881h 29m
162          19861h 27m
163          19871h 19m
164          19781h 28m
165          19861h 36m
166          19771h 21m
167          19741h 24m
168          20041h 58m
169          19901h 25m
170          19831h 30m
171          20001h 55m
172          20081h 39m
173           20032h 5m
174          19841h 33m
175          20051h 47m
176          19911h 33m
177          19781h 28m
178          19831h 25m
179          20081h 21m
180          19831h 30m
181          19851h 32m
182          19781h 11m
183          19781h 19m
184          19841h 27m
185          19751h 17m
186          19841h 33m
187          19871h 34m
188          19841h 22m
189          19851h 25m
190          19791h 23m
191          20081h 49m
192          19781h 22m
193          19801h 16m
194          20081h 39m
195          20071h 40m
196          20001h 53m
197          19891h 32m
198          19861h 23m
199          19811h 21m
200          19751h 18m
201          19781h 26m
202          19871h 36m
203         19741h 26mG
204          20051h 36m
205          19871h 29m
206          19881h 47m
207          19851h 27m
208          19851h 33m
209          19821h 30m
210          19761h 17m
211          19791h 22m
212          19841h 23m
213          20091h 30m
214          19791h 23m
215          20081h 27m
216           19791h 7m
217          19791h 29m
218          19791h 19m
219          19861h 34m
220          19781h 19m
221          20091h 53m
222          19771h 28m
223          20233h 17m
224       20231h 31m18+
225       20192h 12m13+
226       20231h 57m13+
227          20231h 53m
228       20181h 47m15+
229         20143h 16mG
230       20162h 15m13+
231       20231h 54m18+
232         20172h 5m7+
233        20222h 9m16+
234         20183h 8m7+
235         20112h 37mG
236       20132h 14m16+
237       20151h 37m18+
238         20161h 19mG
239     20231h 44mTV-14
240         20152h 16mG
241     20141h 56mTV-14
242       20222h 25m10+
243       20231h 52m18+
244       20121h 30m13+
245        20232h 4m18+
246       20191h 52m15+
247       20122h 45m13A
248        20171h 46m7+
249       20151h 50m13+
250       20231h 45m16+
251         20192h 9m7+
252       20161h 26m13+
253       20231h 37m16+
254       20141h 36m15+
255       20221h 37m13+
256        20181h 49m7+
257       20201h 41m13+
258       20161h 45m13+
259       20121h 47m13+
260          20121h 59m
261        20132h 19m7+
262        20172h 4m13A
263       20211h 36m15+
264        20132h 18m7+
265        20182h 10m7+
266       20141h 45m13A
267       20222h 31m16+
268        20162h 6m15+
269        20192h 21m6+
270       20111h 45m13+
271       20151h 44m15+
272          20222h 22m
273       20151h 52m13+
274        20192h 1m13A
275              20232h
276     20142h 13mTV-MA
277       20171h 55m18+
278        20102h 20m7+
279       20181h 57m13+
280        20221h 33m6+
281       20211h 41m15+
282       20131h 47m15+
283       20182h 16m13+
284        20191h 55m7+
285       20111h 34m16+
286        20141h 58m7+
287          20222h 13m
288        20142h 14m7+
289        20151h 57m7+
290       20191h 49m13+
291        20171h 45m7+
292        20131h 46m7+
293          20131h 53m
294       20211h 36m15+
295        20202h 1m10+
296       20151h 33m18+
297        20142h 5m13+
298       20211h 25m16+
299       20181h 53m13A
300       20171h 48m13A
301        20191h 46m7+
302       20131h 54m13+
303        20182h 1m13+
304       20221h 44m16+
305       20171h 53m13+
306       20221h 52m13+
307         20171h 40mG
308        20191h 39m7+
309       20121h 38m13A
310          20111h 50m
311         20111h 58mG
312        20192h 6m13+
313           20162h13+
314       20191h 48m13+
315          20151h 57m
316        20171h 44m7+
317       20101h 59m13A
318        20111h 32m7+
319       20211h 45m16+
320       20181h 36m13+
321       20152h 40m18+
322       20151h 52m13+
323       20171h 40m15+
324       20211h 55m10+
325       20181h 35m13+
326            20162h7+
327           20191h13+
328       20221h 42m13+
329       20141h 50m15+
330        20201h 58m6+
331          20131h 40m
332        20181h 52m7+
333           20201h10+
334       20161h 44m13+
335       20211h 53m13+
336        20182h 5m13A
337       20171h 50m16+
338       20181h 35m13+
339          20112h 6mG
340       20171h 55m13A
341        20141h 46m7+
342        20161h 49m7+
343       20171h 46m13A
344       20141h 46m13+
345          20131h 37m
346        20131h 32m7+
347       20161h 55m16+
348       20201h 52m13+
349        20181h 50m7+
350          20131h 44m
351        20212h 4m16+
352          20141h 45m
353       20171h 50m13+
354       20161h 41m15+
355          20121h 31m
356        20161h 54m7+
357           20201h10+
358        20181h 54m7+
359        20101h 44m7+
360       20201h 30m18+
361         20131h 39mG
362       20221h 56m13+
363           20191h13+
364        20101h 35m7+
365       20101h 40m13+
366        20151h 53m7+
367       20201h 56m16+
368       20201h 54m10A
369       20151h 48m13+
370        20171h 44m7+
371        20191h 46m7+
372        20171h 48m7+
373          20151h 55m
374        20101h 54m7A
375        20202h 4m13+
376           20192h13+
377       20151h 54m13+
378       20151h 59m15+
379       20141h 43m13A
380       20181h 51m13A
381       20161h 50m15+
382       20141h 57m13A
383        20151h 43m7+
384       20161h 52m13A
385         20141h 45mG
386          20161h 47m
387 20121h 36mNot Rated
388          20121h 46m
389       20191h 50m10+
390          20101h 38m
391          20111h 30m
392        20131h 41m7+
393        20181h 46m7+
394       20101h 42m15+
395       20221h 59m18+
396       20141h 38m15+
397       20141h 42m15+
398         20101h 43mG
399           20122h 5m
400           20152h 6m
401         20111h 46mG
402        20151h 45m7+
403       20171h 43m13+
404       20101h 50m15+
405          20111h 30m
406        20131h 45m7A
407          20101h 45m
408          20111h 45m
409        20181h 53m7+
410        20172h 5m13+
411        20181h 40m7A
412        20172h 30m7A
413         20171h 54mG
414       20171h 54m16+
415       20171h 35m13+
416        20192h 7m18+
417       20181h 45m13+
418       20181h 35m13A
419         20121h 34mG
420          20131h 45m
421     202248mYETİŞKİN
422        20161h 40m7+
423        20161h 54m7+
424          20151h 37m
425          20121h 41m
426       20111h 45m13+
427              20112h
428        20161h 33m7+
429          20151h 39m
430          20112h 43m
431          20131h 37m
432        20101h 42m7+
433       20181h 56m13A
434        20141h 47m7+
435       20101h 44m13A
436          20111h 30m
437       20151h 58m13A
438        20121h 38m7A
439          20131h 40m
440         20101h 36mG
441       20161h 49m13+
442        20171h 48m7+
443       20161h 48m13+
444           20142h 6m
445       20111h 44m15A
446        20171h 30m7A
447        20191h 30m7+
448        20141h 49m7+
449        20151h 58m7A
450       20181h 42m15+
451         20131h 33mG
452           20182h13A
453        20161h 47m7+
454          20111h 42m
455         20141h 49mG
456          20111h 51m
457        20151h 46m7A
458       20151h 33m13A
459          20141h 36m
460          20171h 56m
461          20101h 35m
462       20121h 41m15+
463          20201h 10m
464        20151h 54m7+
465        20171h 13mPG
466          20161h 28m
467          20211h 35m
468        20181h 36m7+
469          20151h 31m
470             201856m</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>df_durations</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Durations
1       2h 8m
2      1h 48m
3      1h 50m
4      1h 43m
5      1h 50m
6       2h 8m
7       2h 7m
8      1h 26m
9      1h 27m
10     1h 49m
11     1h 32m
12      2h 7m
13     2h 20m
14     1h 59m
15     1h 53m
16      2h 2m
17     1h 47m
18     1h 52m
19     1h 50m
20     1h 37m
21     1h 50m
22     1h 47m
23     1h 39m
24     1h 31m
25     1h 30m
26     1h 32m
27         2h
28     1h 15m
29     1h 46m
30     1h 42m
31     1h 30m
32     1h 40m
33     1h 50m
34     1h 32m
35      2h 8m
36     1h 30m
37     2h 10m
38      2h 3m
39     1h 38m
40     1h 30m
41     1h 30m
42     1h 29m
43     1h 25m
44     1h 25m
45         2h
46         2h
47     1h 20m
48     1h 37m
49     1h 38m
50     1h 36m
51     1h 30m
52     1h 40m
53     1h 47m
54     1h 32m
55     2h 22m
56     1h 37m
57     1h 40m
58      2h 2m
59     1h 41m
60     1h 39m
61     1h 28m
62     1h 59m
63     1h 39m
64     1h 57m
65     1h 15m
66     1h 27m
67     1h 26m
68     1h 37m
69     1h 35m
70     1h 41m
71     1h 28m
72      2h 2m
73     1h 20m
74     1h 54m
75     1h 23m
76     1h 57m
77     1h 45m
78      2h 2m
79     1h 37m
80     1h 33m
81         2h
82     1h 45m
83     1h 43m
84     1h 35m
85     1h 46m
86     1h 40m
87     1h 42m
88         2h
89     1h 35m
90     1h 34m
91     1h 29m
92     1h 45m
93     1h 30m
94     1h 55m
95     1h 25m
96         2h
97     1h 59m
98     1h 35m
99     1h 52m
100    1h 30m
101    2h 15m
102    1h 55m
103    1h 40m
104    1h 25m
105    1h 51m
106    1h 17m
107    1h 30m
108    1h 23m
109    1h 29m
110    1h 25m
111    1h 42m
112    1h 40m
113    1h 37m
114    1h 53m
115    1h 32m
116    1h 31m
117    1h 59m
118    1h 35m
119    1h 44m
120    2h 10m
121    1h 46m
122    1h 12m
123    1h 40m
124    1h 16m
125    1h 25m
126    1h 35m
127    1h 51m
128    1h 56m
129    1h 45m
130    1h 14m
131        2h
132    1h 34m
133    1h 27m
134    1h 24m
135    1h 37m
136     2h 1m
137    1h 52m
138    1h 53m
139    1h 38m
140    1h 17m
141     2h 6m
142    1h 32m
143    1h 21m
144    1h 50m
145    1h 27m
146    1h 34m
147    1h 40m
148    1h 33m
149    1h 40m
150    1h 24m
151    1h 21m
152    1h 19m
153    1h 31m
154    1h 45m
155     2h 8m
156    1h 31m
157    2h 17m
158    1h 37m
159    1h 52m
160    1h 40m
161    1h 29m
162    1h 27m
163    1h 19m
164    1h 28m
165    1h 36m
166    1h 21m
167    1h 24m
168    1h 58m
169    1h 25m
170    1h 30m
171    1h 55m
172    1h 39m
173     2h 5m
174    1h 33m
175    1h 47m
176    1h 33m
177    1h 28m
178    1h 25m
179    1h 21m
180    1h 30m
181    1h 32m
182    1h 11m
183    1h 19m
184    1h 27m
185    1h 17m
186    1h 33m
187    1h 34m
188    1h 22m
189    1h 25m
190    1h 23m
191    1h 49m
192    1h 22m
193    1h 16m
194    1h 39m
195    1h 40m
196    1h 53m
197    1h 32m
198    1h 23m
199    1h 21m
200    1h 18m
201    1h 26m
202    1h 36m
203    1h 26m
204    1h 36m
205    1h 29m
206    1h 47m
207    1h 27m
208    1h 33m
209    1h 30m
210    1h 17m
211    1h 22m
212    1h 23m
213    1h 30m
214    1h 23m
215    1h 27m
216     1h 7m
217    1h 29m
218    1h 19m
219    1h 34m
220    1h 19m
221    1h 53m
222    1h 28m
223    3h 17m
224    1h 31m
225    2h 12m
226    1h 57m
227    1h 53m
228    1h 47m
229    3h 16m
230    2h 15m
231    1h 54m
232     2h 5m
233     2h 9m
234     3h 8m
235    2h 37m
236    2h 14m
237    1h 37m
238    1h 19m
239    1h 44m
240    2h 16m
241    1h 56m
242    2h 25m
243    1h 52m
244    1h 30m
245     2h 4m
246    1h 52m
247    2h 45m
248    1h 46m
249    1h 50m
250    1h 45m
251     2h 9m
252    1h 26m
253    1h 37m
254    1h 36m
255    1h 37m
256    1h 49m
257    1h 41m
258    1h 45m
259    1h 47m
260    1h 59m
261    2h 19m
262     2h 4m
263    1h 36m
264    2h 18m
265    2h 10m
266    1h 45m
267    2h 31m
268     2h 6m
269    2h 21m
270    1h 45m
271    1h 44m
272    2h 22m
273    1h 52m
274     2h 1m
275        2h
276    2h 13m
277    1h 55m
278    2h 20m
279    1h 57m
280    1h 33m
281    1h 41m
282    1h 47m
283    2h 16m
284    1h 55m
285    1h 34m
286    1h 58m
287    2h 13m
288    2h 14m
289    1h 57m
290    1h 49m
291    1h 45m
292    1h 46m
293    1h 53m
294    1h 36m
295     2h 1m
296    1h 33m
297     2h 5m
298    1h 25m
299    1h 53m
300    1h 48m
301    1h 46m
302    1h 54m
303     2h 1m
304    1h 44m
305    1h 53m
306    1h 52m
307    1h 40m
308    1h 39m
309    1h 38m
310    1h 50m
311    1h 58m
312     2h 6m
313        2h
314    1h 48m
315    1h 57m
316    1h 44m
317    1h 59m
318    1h 32m
319    1h 45m
320    1h 36m
321    2h 40m
322    1h 52m
323    1h 40m
324    1h 55m
325    1h 35m
326        2h
327        1h
328    1h 42m
329    1h 50m
330    1h 58m
331    1h 40m
332    1h 52m
333        1h
334    1h 44m
335    1h 53m
336     2h 5m
337    1h 50m
338    1h 35m
339     2h 6m
340    1h 55m
341    1h 46m
342    1h 49m
343    1h 46m
344    1h 46m
345    1h 37m
346    1h 32m
347    1h 55m
348    1h 52m
349    1h 50m
350    1h 44m
351     2h 4m
352    1h 45m
353    1h 50m
354    1h 41m
355    1h 31m
356    1h 54m
357        1h
358    1h 54m
359    1h 44m
360    1h 30m
361    1h 39m
362    1h 56m
363        1h
364    1h 35m
365    1h 40m
366    1h 53m
367    1h 56m
368    1h 54m
369    1h 48m
370    1h 44m
371    1h 46m
372    1h 48m
373    1h 55m
374    1h 54m
375     2h 4m
376        2h
377    1h 54m
378    1h 59m
379    1h 43m
380    1h 51m
381    1h 50m
382    1h 57m
383    1h 43m
384    1h 52m
385    1h 45m
386    1h 47m
387    1h 36m
388    1h 46m
389    1h 50m
390    1h 38m
391    1h 30m
392    1h 41m
393    1h 46m
394    1h 42m
395    1h 59m
396    1h 38m
397    1h 42m
398    1h 43m
399     2h 5m
400     2h 6m
401    1h 46m
402    1h 45m
403    1h 43m
404    1h 50m
405    1h 30m
406    1h 45m
407    1h 45m
408    1h 45m
409    1h 53m
410     2h 5m
411    1h 40m
412    2h 30m
413    1h 54m
414    1h 54m
415    1h 35m
416     2h 7m
417    1h 45m
418    1h 35m
419    1h 34m
420    1h 45m
421       48m
422    1h 40m
423    1h 54m
424    1h 37m
425    1h 41m
426    1h 45m
427        2h
428    1h 33m
429    1h 39m
430    2h 43m
431    1h 37m
432    1h 42m
433    1h 56m
434    1h 47m
435    1h 44m
436    1h 30m
437    1h 58m
438    1h 38m
439    1h 40m
440    1h 36m
441    1h 49m
442    1h 48m
443    1h 48m
444     2h 6m
445    1h 44m
446    1h 30m
447    1h 30m
448    1h 49m
449    1h 58m
450    1h 42m
451    1h 33m
452        2h
453    1h 47m
454    1h 42m
455    1h 49m
456    1h 51m
457    1h 46m
458    1h 33m
459    1h 36m
460    1h 56m
461    1h 35m
462    1h 41m
463    1h 10m
464    1h 54m
465    1h 13m
466    1h 28m
467    1h 35m
468    1h 36m
469    1h 31m
470       56m</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>df_ratings</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Ratings
1    8.0&nbsp;(35K)
2    8.2&nbsp;(91K)
3    8.1&nbsp;(19K)
4    7.8&nbsp;(16K)
5    7.5&nbsp;(22K)
6    8.1&nbsp;(72K)
7    7.3&nbsp;(45K)
8   8.0&nbsp;(7.1K)
9    9.2&nbsp;(43K)
10   7.3&nbsp;(23K)
11   7.0&nbsp;(15K)
12   8.0&nbsp;(66K)
13   7.8&nbsp;(24K)
14  7.5&nbsp;(6.7K)
15   6.8&nbsp;(22K)
16   5.7&nbsp;(18K)
17   8.0&nbsp;(14K)
18   7.4&nbsp;(38K)
19  4.4&nbsp;(4.7K)
20   7.1&nbsp;(14K)
21   8.0&nbsp;(38K)
22   8.1&nbsp;(27K)
23   8.1&nbsp;(23K)
24    4.4&nbsp;(8K)
25   8.9&nbsp;(24K)
26  6.3&nbsp;(3.2K)
27   7.6&nbsp;(12K)
28   7.7&nbsp;(11K)
29   7.4&nbsp;(35K)
30   7.9&nbsp;(16K)
31   8.5&nbsp;(17K)
32  7.0&nbsp;(3.9K)
33   1.5&nbsp;(17K)
34  7.3&nbsp;(4.3K)
35   7.4&nbsp;(12K)
36   8.7&nbsp;(19K)
37  7.3&nbsp;(6.6K)
38  6.5&nbsp;(4.1K)
39   6.5&nbsp;(14K)
40  7.8&nbsp;(5.5K)
41   4.8&nbsp;(28K)
42  7.0&nbsp;(6.1K)
43  7.0&nbsp;(6.4K)
44  3.0&nbsp;(2.7K)
45   6.6&nbsp;(11K)
46   6.6&nbsp;(11K)
47   8.5&nbsp;(21K)
48  6.6&nbsp;(5.6K)
49  7.3&nbsp;(7.1K)
50  6.5&nbsp;(3.5K)
51  3.9&nbsp;(3.2K)
52   7.5&nbsp;(14K)
53   4.5&nbsp;(22K)
54  6.1&nbsp;(3.4K)
55   7.8&nbsp;(10K)
56  6.2&nbsp;(5.3K)
57  7.8&nbsp;(3.5K)
58   7.4&nbsp;(34K)
59   8.7&nbsp;(16K)
60  7.7&nbsp;(6.7K)
61  7.7&nbsp;(6.1K)
62   8.4&nbsp;(12K)
63  7.3&nbsp;(6.9K)
64  8.0&nbsp;(4.4K)
65  7.2&nbsp;(4.2K)
66  7.4&nbsp;(6.4K)
67  6.7&nbsp;(3.3K)
68  7.8&nbsp;(6.5K)
69   8.7&nbsp;(12K)
70  7.5&nbsp;(4.4K)
71   8.5&nbsp;(11K)
72  7.1&nbsp;(5.1K)
73   8.8&nbsp;(21K)
74    7.2&nbsp;(7K)
75   8.7&nbsp;(17K)
76  8.2&nbsp;(5.3K)
77  4.2&nbsp;(3.6K)
78  6.3&nbsp;(5.8K)
79  5.9&nbsp;(7.5K)
80    6.7&nbsp;(3K)
81   7.1&nbsp;(10K)
82  7.5&nbsp;(7.8K)
83  7.7&nbsp;(3.7K)
84  7.9&nbsp;(3.4K)
85  7.2&nbsp;(8.1K)
86  1.9&nbsp;(3.9K)
87  7.6&nbsp;(6.5K)
88   8.0&nbsp;(13K)
89   8.9&nbsp;(24K)
90  7.1&nbsp;(2.8K)
91  7.9&nbsp;(3.2K)
92  5.1&nbsp;(9.8K)
93  7.8&nbsp;(3.2K)
94  6.2&nbsp;(3.1K)
95   8.6&nbsp;(10K)
96  7.3&nbsp;(3.3K)
97  7.5&nbsp;(9.7K)
98  5.9&nbsp;(4.4K)
99  6.1&nbsp;(2.6K)
100 6.3&nbsp;(2.6K)
101  7.5&nbsp;(13K)
102 6.5&nbsp;(7.3K)
103 8.0&nbsp;(4.2K)
104 8.3&nbsp;(7.1K)
105  6.5&nbsp;(16K)
106 8.1&nbsp;(7.2K)
107 7.6&nbsp;(4.8K)
108 7.7&nbsp;(6.2K)
109 4.4&nbsp;(6.1K)
110 6.9&nbsp;(3.6K)
111 6.6&nbsp;(3.3K)
112 6.1&nbsp;(7.5K)
113  8.6&nbsp;(19K)
114   7.2&nbsp;(4K)
115 8.0&nbsp;(8.3K)
116  8.3&nbsp;(12K)
117 7.0&nbsp;(3.8K)
118 8.0&nbsp;(3.8K)
119 3.8&nbsp;(5.3K)
120 6.7&nbsp;(2.8K)
121 7.6&nbsp;(4.2K)
122 7.2&nbsp;(3.6K)
123 4.1&nbsp;(3.6K)
124 7.8&nbsp;(9.6K)
125 7.6&nbsp;(7.4K)
126 3.0&nbsp;(3.9K)
127 7.3&nbsp;(4.4K)
128   5.0&nbsp;(4K)
129 1.6&nbsp;(9.6K)
130 7.5&nbsp;(4.9K)
131 6.4&nbsp;(5.4K)
132  8.7&nbsp;(21K)
133  8.0&nbsp;(11K)
134  8.4&nbsp;(13K)
135 8.4&nbsp;(7.6K)
136 7.3&nbsp;(3.4K)
137 7.2&nbsp;(2.9K)
138 6.6&nbsp;(6.2K)
139 3.0&nbsp;(8.7K)
140   7.3&nbsp;(3K)
141 6.9&nbsp;(6.8K)
142 8.4&nbsp;(7.2K)
143 7.1&nbsp;(3.4K)
144 7.2&nbsp;(2.8K)
145 6.9&nbsp;(4.1K)
146 8.1&nbsp;(9.2K)
147 7.5&nbsp;(3.7K)
148 7.3&nbsp;(4.9K)
149 6.6&nbsp;(6.5K)
150 7.7&nbsp;(7.5K)
151 6.3&nbsp;(6.2K)
152 6.9&nbsp;(2.6K)
153 6.9&nbsp;(4.1K)
154 7.2&nbsp;(2.6K)
155 7.5&nbsp;(3.3K)
156   7.3&nbsp;(3K)
157 6.2&nbsp;(2.8K)
158 2.4&nbsp;(4.3K)
159 3.3&nbsp;(7.8K)
160 5.2&nbsp;(7.2K)
161 7.2&nbsp;(2.6K)
162 7.3&nbsp;(3.7K)
163 7.1&nbsp;(3.4K)
164 7.5&nbsp;(3.8K)
165 7.1&nbsp;(4.3K)
166   8.0&nbsp;(9K)
167 7.9&nbsp;(7.8K)
168   3.2&nbsp;(7K)
169 7.0&nbsp;(2.6K)
170 7.1&nbsp;(2.7K)
171 7.0&nbsp;(2.8K)
172   5.5&nbsp;(3K)
173 4.9&nbsp;(2.7K)
174 6.2&nbsp;(3.7K)
175 6.3&nbsp;(4.7K)
176 6.6&nbsp;(2.8K)
177 7.3&nbsp;(8.9K)
178 7.0&nbsp;(3.5K)
179 7.4&nbsp;(3.1K)
180 7.9&nbsp;(6.7K)
181 6.9&nbsp;(3.5K)
182 7.5&nbsp;(4.4K)
183 7.7&nbsp;(5.9K)
184 7.0&nbsp;(4.6K)
185 6.3&nbsp;(4.4K)
186 8.1&nbsp;(7.4K)
187 6.7&nbsp;(2.7K)
188   7.2&nbsp;(5K)
189 6.5&nbsp;(4.1K)
190 7.5&nbsp;(3.2K)
191 6.8&nbsp;(4.8K)
192   7.1&nbsp;(3K)
193 7.1&nbsp;(3.1K)
194 6.9&nbsp;(2.6K)
195   1.5&nbsp;(7K)
196 5.8&nbsp;(3.4K)
197 7.0&nbsp;(2.9K)
198 6.4&nbsp;(3.2K)
199 6.8&nbsp;(3.9K)
200 6.8&nbsp;(2.7K)
201 6.9&nbsp;(4.5K)
202 7.5&nbsp;(4.6K)
203 7.2&nbsp;(3.2K)
204 4.4&nbsp;(3.3K)
205 6.1&nbsp;(3.8K)
206 7.7&nbsp;(3.9K)
207 6.5&nbsp;(3.3K)
208   6.4&nbsp;(3K)
209 7.2&nbsp;(2.7K)
210 7.6&nbsp;(6.3K)
211 7.6&nbsp;(6.6K)
212 7.6&nbsp;(5.1K)
213 7.0&nbsp;(2.7K)
214 7.1&nbsp;(3.6K)
215 3.1&nbsp;(5.6K)
216 6.9&nbsp;(2.7K)
217 7.5&nbsp;(4.4K)
218 7.2&nbsp;(4.1K)
219 6.5&nbsp;(2.7K)
220   7.1&nbsp;(3K)
221 5.0&nbsp;(3.9K)
222 6.1&nbsp;(3.5K)
223 8.1&nbsp;(5.1K)
224 5.3&nbsp;(7.4K)
225  8.2&nbsp;(54K)
226 7.5&nbsp;(3.5K)
227 3.6&nbsp;(3.4K)
228  7.6&nbsp;(30K)
229  8.0&nbsp;(55K)
230 8.2&nbsp;(110K)
231 6.3&nbsp;(8.8K)
232  8.3&nbsp;(43K)
233  7.6&nbsp;(11K)
234  8.0&nbsp;(27K)
235  7.8&nbsp;(49K)
236 6.8&nbsp;(7.1K)
237  5.8&nbsp;(12K)
238  7.6&nbsp;(16K)
239 5.6&nbsp;(2.6K)
240  7.6&nbsp;(14K)
241 6.4&nbsp;(3.5K)
242 6.9&nbsp;(5.9K)
243 5.7&nbsp;(4.5K)
244  7.5&nbsp;(23K)
245 6.5&nbsp;(5.2K)
246  6.7&nbsp;(19K)
247  6.5&nbsp;(59K)
248  6.4&nbsp;(27K)
249  7.4&nbsp;(14K)
250 6.2&nbsp;(4.8K)
251 7.2&nbsp;(2.8K)
252 7.0&nbsp;(8.4K)
253 5.3&nbsp;(3.1K)
254   6.0&nbsp;(5K)
255 5.3&nbsp;(5.8K)
256 5.5&nbsp;(3.7K)
257 6.9&nbsp;(2.5K)
258 6.5&nbsp;(2.8K)
259  7.1&nbsp;(10K)
260 5.8&nbsp;(4.2K)
261  9.1&nbsp;(47K)
262  7.6&nbsp;(26K)
263  6.6&nbsp;(13K)
264  7.7&nbsp;(24K)
265  8.2&nbsp;(13K)
266 7.3&nbsp;(5.9K)
267 7.1&nbsp;(5.6K)
268 6.1&nbsp;(7.3K)
269  8.2&nbsp;(14K)
270  7.5&nbsp;(25K)
271  7.9&nbsp;(13K)
272 5.8&nbsp;(4.4K)
273 6.2&nbsp;(2.7K)
274  6.0&nbsp;(16K)
275 6.8&nbsp;(6.8K)
276 5.9&nbsp;(4.3K)
277 7.0&nbsp;(4.4K)
278  7.4&nbsp;(36K)
279  7.3&nbsp;(16K)
280 6.6&nbsp;(2.6K)
281 6.3&nbsp;(3.4K)
282  7.7&nbsp;(10K)
283  7.6&nbsp;(20K)
284 7.0&nbsp;(7.4K)
285  6.5&nbsp;(14K)
286  7.5&nbsp;(13K)
287 5.2&nbsp;(6.4K)
288  7.3&nbsp;(35K)
289  6.7&nbsp;(12K)
290 7.1&nbsp;(6.3K)
291 3.9&nbsp;(3.3K)
292  6.9&nbsp;(24K)
293 6.1&nbsp;(4.9K)
294  6.0&nbsp;(11K)
295 5.6&nbsp;(5.8K)
296 6.1&nbsp;(3.7K)
297 6.9&nbsp;(4.1K)
298   7.4&nbsp;(3K)
299   6.2&nbsp;(5K)
300 5.9&nbsp;(5.8K)
301 6.1&nbsp;(3.1K)
302  3.1&nbsp;(43K)
303 5.1&nbsp;(3.5K)
304 5.7&nbsp;(3.7K)
305 4.8&nbsp;(4.7K)
306   6.4&nbsp;(4K)
307 6.0&nbsp;(2.8K)
308 1.4&nbsp;(9.5K)
309 6.3&nbsp;(6.5K)
310  7.5&nbsp;(10K)
311  7.2&nbsp;(19K)
312 6.5&nbsp;(6.4K)
313 7.3&nbsp;(4.1K)
314 7.4&nbsp;(4.7K)
315 6.5&nbsp;(3.4K)
316 7.6&nbsp;(5.5K)
317  5.7&nbsp;(15K)
318 5.8&nbsp;(7.9K)
319 5.5&nbsp;(4.8K)
320   5.7&nbsp;(3K)
321 5.6&nbsp;(3.2K)
322  6.3&nbsp;(11K)
323  1.0&nbsp;(39K)
324 6.5&nbsp;(3.6K)
325 6.8&nbsp;(2.9K)
326   5.8&nbsp;(5K)
327  5.5&nbsp;(10K)
328   5.7&nbsp;(3K)
329  7.7&nbsp;(14K)
330   5.8&nbsp;(5K)
331 7.5&nbsp;(5.7K)
332 7.0&nbsp;(3.8K)
333 6.5&nbsp;(9.1K)
334 5.6&nbsp;(4.6K)
335 6.2&nbsp;(5.5K)
336  7.0&nbsp;(39K)
337 5.8&nbsp;(5.4K)
338 6.8&nbsp;(9.4K)
339  8.0&nbsp;(11K)
340 6.1&nbsp;(7.5K)
341  7.1&nbsp;(11K)
342 5.0&nbsp;(3.5K)
343 5.6&nbsp;(2.6K)
344 6.6&nbsp;(3.7K)
345 7.4&nbsp;(6.9K)
346 7.0&nbsp;(5.5K)
347  7.3&nbsp;(15K)
348 3.7&nbsp;(7.9K)
349  2.0&nbsp;(56K)
350 6.2&nbsp;(2.6K)
351 7.0&nbsp;(3.1K)
352 6.3&nbsp;(3.3K)
353 5.6&nbsp;(6.8K)
354 3.7&nbsp;(3.2K)
355 5.0&nbsp;(6.1K)
356 7.1&nbsp;(7.8K)
357 5.6&nbsp;(7.7K)
358   4.5&nbsp;(4K)
359 4.5&nbsp;(5.2K)
360 5.6&nbsp;(5.4K)
361 6.5&nbsp;(9.2K)
362 5.3&nbsp;(5.3K)
363  6.4&nbsp;(13K)
364  4.2&nbsp;(21K)
365 6.3&nbsp;(2.6K)
366 6.0&nbsp;(3.8K)
367 4.6&nbsp;(3.5K)
368 4.6&nbsp;(4.2K)
369 6.1&nbsp;(5.4K)
370 5.5&nbsp;(3.1K)
371 2.2&nbsp;(3.8K)
372  1.0&nbsp;(74K)
373 3.8&nbsp;(3.5K)
374 7.2&nbsp;(7.5K)
375 7.1&nbsp;(3.2K)
376 6.4&nbsp;(5.2K)
377  5.6&nbsp;(21K)
378 7.2&nbsp;(4.3K)
379 6.0&nbsp;(4.6K)
380 6.7&nbsp;(4.7K)
381   6.1&nbsp;(3K)
382  3.8&nbsp;(18K)
383  7.3&nbsp;(16K)
384 2.6&nbsp;(2.6K)
385 5.9&nbsp;(7.9K)
386 6.8&nbsp;(3.7K)
387 7.1&nbsp;(2.8K)
388 6.2&nbsp;(2.7K)
389 3.0&nbsp;(8.6K)
390 3.0&nbsp;(5.5K)
391  7.0&nbsp;(14K)
392 7.1&nbsp;(5.1K)
393 4.7&nbsp;(2.8K)
394 5.6&nbsp;(7.3K)
395 6.5&nbsp;(2.7K)
396 4.9&nbsp;(3.5K)
397   5.0&nbsp;(3K)
398 7.1&nbsp;(7.4K)
399 7.5&nbsp;(6.1K)
400 7.1&nbsp;(4.2K)
401  6.6&nbsp;(15K)
402 6.7&nbsp;(9.6K)
403 6.7&nbsp;(5.2K)
404 7.4&nbsp;(6.1K)
405 3.7&nbsp;(3.2K)
406 6.1&nbsp;(5.2K)
407 6.5&nbsp;(5.5K)
408 5.2&nbsp;(2.6K)
409 6.1&nbsp;(7.9K)
410 2.0&nbsp;(2.9K)
411  1.2&nbsp;(10K)
412 6.7&nbsp;(4.3K)
413 6.1&nbsp;(2.7K)
414  3.4&nbsp;(18K)
415 5.6&nbsp;(3.6K)
416 6.3&nbsp;(3.1K)
417 2.2&nbsp;(3.6K)
418   3.0&nbsp;(3K)
419 7.2&nbsp;(3.9K)
420 5.2&nbsp;(3.6K)
421 1.2&nbsp;(9.9K)
422 5.6&nbsp;(3.9K)
423 3.5&nbsp;(6.8K)
424  5.4&nbsp;(18K)
425 5.0&nbsp;(5.4K)
426 6.1&nbsp;(9.5K)
427 6.2&nbsp;(5.6K)
428 4.1&nbsp;(4.9K)
429 5.8&nbsp;(3.9K)
430 4.6&nbsp;(3.6K)
431 5.3&nbsp;(5.4K)
432 5.5&nbsp;(5.2K)
433 5.9&nbsp;(3.7K)
434 4.6&nbsp;(4.9K)
435  7.0&nbsp;(21K)
436 6.4&nbsp;(3.4K)
437 5.4&nbsp;(3.3K)
438 5.2&nbsp;(7.2K)
439 3.1&nbsp;(2.7K)
440 6.4&nbsp;(4.5K)
441   4.1&nbsp;(3K)
442 6.2&nbsp;(4.5K)
443 5.7&nbsp;(3.5K)
444 7.5&nbsp;(4.1K)
445 7.1&nbsp;(2.8K)
446   1.6&nbsp;(7K)
447 1.4&nbsp;(4.8K)
448 6.6&nbsp;(4.8K)
449 6.3&nbsp;(3.9K)
450 3.8&nbsp;(2.6K)
451 6.8&nbsp;(3.5K)
452 7.4&nbsp;(2.9K)
453   6.2&nbsp;(3K)
454   6.8&nbsp;(4K)
455 6.0&nbsp;(7.1K)
456 6.6&nbsp;(3.6K)
457 4.5&nbsp;(3.5K)
458 5.9&nbsp;(3.6K)
459 5.4&nbsp;(4.3K)
460 5.6&nbsp;(4.9K)
461 5.3&nbsp;(5.3K)
462   4.6&nbsp;(4K)
463 2.7&nbsp;(2.7K)
464  1.7&nbsp;(28K)
465 7.7&nbsp;(3.3K)
466 4.7&nbsp;(2.7K)
467  1.2&nbsp;(21K)
468 4.9&nbsp;(2.6K)
469 1.7&nbsp;(3.7K)
470 7.2&nbsp;(2.6K)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>df_votes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Votes
1    Votes35,024
2    Votes91,040
3    Votes19,298
4    Votes16,267
5    Votes22,374
6    Votes71,705
7    Votes44,635
8     Votes7,133
9    Votes42,513
10   Votes22,667
11   Votes14,685
12   Votes66,033
13   Votes23,635
14    Votes6,718
15   Votes22,340
16   Votes18,253
17   Votes14,307
18   Votes37,785
19    Votes4,734
20   Votes14,007
21   Votes38,405
22   Votes27,122
23   Votes22,669
24    Votes8,014
25   Votes24,329
26    Votes3,166
27   Votes11,725
28   Votes10,854
29   Votes35,029
30   Votes15,724
31   Votes16,724
32    Votes3,923
33   Votes16,706
34    Votes4,265
35   Votes12,406
36   Votes18,534
37    Votes6,629
38    Votes4,121
39   Votes13,656
40    Votes5,494
41   Votes28,355
42    Votes6,060
43    Votes6,426
44    Votes2,661
45   Votes11,254
46   Votes10,575
47   Votes21,181
48    Votes5,596
49    Votes7,087
50    Votes3,464
51    Votes3,211
52   Votes13,504
53   Votes22,333
54    Votes3,374
55   Votes10,406
56    Votes5,288
57    Votes3,498
58   Votes34,181
59   Votes16,137
60    Votes6,741
61    Votes6,089
62   Votes11,522
63    Votes6,865
64    Votes4,383
65    Votes4,199
66    Votes6,438
67    Votes3,314
68    Votes6,466
69   Votes11,807
70    Votes4,444
71   Votes10,565
72    Votes5,130
73   Votes20,889
74    Votes7,031
75   Votes17,126
76    Votes5,259
77    Votes3,640
78    Votes5,818
79    Votes7,513
80    Votes3,026
81   Votes10,029
82    Votes7,798
83    Votes3,721
84    Votes3,387
85    Votes8,141
86    Votes3,899
87    Votes6,495
88   Votes12,609
89   Votes24,369
90    Votes2,805
91    Votes3,249
92    Votes9,842
93    Votes3,207
94    Votes3,141
95   Votes10,097
96    Votes3,275
97    Votes9,741
98    Votes4,350
99    Votes2,555
100   Votes2,628
101  Votes13,079
102   Votes7,339
103   Votes4,245
104   Votes7,078
105  Votes16,375
106   Votes7,222
107   Votes4,761
108   Votes6,177
109   Votes6,059
110   Votes3,644
111   Votes3,317
112   Votes7,525
113  Votes18,636
114   Votes4,025
115   Votes8,302
116  Votes11,647
117   Votes3,821
118   Votes3,792
119   Votes5,257
120   Votes2,844
121   Votes4,243
122   Votes3,636
123   Votes3,632
124   Votes9,553
125   Votes7,352
126   Votes3,920
127   Votes4,372
128   Votes4,027
129   Votes9,616
130   Votes4,936
131   Votes5,446
132  Votes20,640
133  Votes11,021
134  Votes13,359
135   Votes7,591
136   Votes3,432
137   Votes2,938
138   Votes6,235
139   Votes8,696
140   Votes3,000
141   Votes6,803
142   Votes7,213
143   Votes3,403
144   Votes2,793
145   Votes4,069
146   Votes9,204
147   Votes3,713
148   Votes4,948
149   Votes6,542
150   Votes7,477
151   Votes6,186
152   Votes2,578
153   Votes4,113
154   Votes2,602
155   Votes3,289
156   Votes2,999
157   Votes2,767
158   Votes4,276
159   Votes7,787
160   Votes7,220
161   Votes2,620
162   Votes3,727
163   Votes3,420
164   Votes3,830
165   Votes4,270
166   Votes8,952
167   Votes7,833
168   Votes6,964
169   Votes2,633
170   Votes2,712
171   Votes2,806
172   Votes3,019
173   Votes2,742
174   Votes3,708
175   Votes4,661
176   Votes2,820
177   Votes8,939
178   Votes3,468
179   Votes3,089
180   Votes6,746
181   Votes3,528
182   Votes4,382
183   Votes5,934
184   Votes4,602
185   Votes4,367
186   Votes7,353
187   Votes2,714
188   Votes4,955
189   Votes4,137
190   Votes3,248
191   Votes4,834
192   Votes3,037
193   Votes3,139
194   Votes2,562
195   Votes7,047
196   Votes3,433
197   Votes2,902
198   Votes3,154
199   Votes3,933
200   Votes2,737
201   Votes4,459
202   Votes4,554
203   Votes3,218
204   Votes3,260
205   Votes3,783
206   Votes3,905
207   Votes3,284
208   Votes2,973
209   Votes2,677
210   Votes6,252
211   Votes6,579
212   Votes5,137
213   Votes2,736
214   Votes3,582
215   Votes5,552
216   Votes2,710
217   Votes4,350
218   Votes4,090
219   Votes2,711
220   Votes3,025
221   Votes3,908
222   Votes3,498
223   Votes5,099
224   Votes7,408
225  Votes54,178
226   Votes3,508
227   Votes3,360
228  Votes30,274
229  Votes54,651
230 Votes109,871
231   Votes8,785
232  Votes42,995
233  Votes11,172
234  Votes27,020
235  Votes49,372
236   Votes7,112
237  Votes12,110
238  Votes15,614
239   Votes2,587
240  Votes13,900
241   Votes3,505
242   Votes5,868
243   Votes4,481
244  Votes23,122
245   Votes5,157
246  Votes19,223
247  Votes58,914
248  Votes26,555
249  Votes14,325
250   Votes4,758
251   Votes2,785
252   Votes8,439
253   Votes3,089
254   Votes5,040
255   Votes5,827
256   Votes3,655
257   Votes2,519
258   Votes2,843
259  Votes10,090
260   Votes4,207
261  Votes46,997
262  Votes25,667
263  Votes13,419
264  Votes23,764
265  Votes13,032
266   Votes5,938
267   Votes5,622
268   Votes7,285
269  Votes13,655
270  Votes25,130
271  Votes13,134
272   Votes4,416
273   Votes2,724
274  Votes15,827
275   Votes6,799
276   Votes4,277
277   Votes4,370
278  Votes36,265
279  Votes15,789
280   Votes2,589
281   Votes3,391
282  Votes10,485
283  Votes19,957
284   Votes7,412
285  Votes14,119
286  Votes12,922
287   Votes6,370
288  Votes35,457
289  Votes12,124
290   Votes6,290
291   Votes3,334
292  Votes23,519
293   Votes4,881
294  Votes11,271
295   Votes5,809
296   Votes3,707
297   Votes4,069
298   Votes2,954
299   Votes4,995
300   Votes5,761
301   Votes3,103
302  Votes43,233
303   Votes3,488
304   Votes3,726
305   Votes4,708
306   Votes4,009
307   Votes2,789
308   Votes9,516
309   Votes6,501
310  Votes10,399
311  Votes19,483
312   Votes6,394
313   Votes4,132
314   Votes4,663
315   Votes3,400
316   Votes5,511
317  Votes15,445
318   Votes7,949
319   Votes4,789
320   Votes2,961
321   Votes3,182
322  Votes11,164
323  Votes39,269
324   Votes3,595
325   Votes2,877
326   Votes5,010
327  Votes10,470
328   Votes2,994
329  Votes13,675
330   Votes5,008
331   Votes5,738
332   Votes3,781
333   Votes9,140
334   Votes4,551
335   Votes5,489
336  Votes38,570
337   Votes5,368
338   Votes9,431
339  Votes11,218
340   Votes7,478
341  Votes10,860
342   Votes3,472
343   Votes2,613
344   Votes3,732
345   Votes6,858
346   Votes5,487
347  Votes15,308
348   Votes7,870
349  Votes55,886
350   Votes2,619
351   Votes3,095
352   Votes3,273
353   Votes6,822
354   Votes3,196
355   Votes6,095
356   Votes7,831
357   Votes7,650
358   Votes3,961
359   Votes5,160
360   Votes5,418
361   Votes9,181
362   Votes5,265
363  Votes13,414
364  Votes20,792
365   Votes2,599
366   Votes3,849
367   Votes3,539
368   Votes4,200
369   Votes5,428
370   Votes3,124
371   Votes3,849
372  Votes73,974
373   Votes3,526
374   Votes7,481
375   Votes3,211
376   Votes5,221
377  Votes20,982
378   Votes4,320
379   Votes4,594
380   Votes4,652
381   Votes3,018
382  Votes18,081
383  Votes16,479
384   Votes2,632
385   Votes7,920
386   Votes3,659
387   Votes2,834
388   Votes2,710
389   Votes8,627
390   Votes5,455
391  Votes13,541
392   Votes5,094
393   Votes2,830
394   Votes7,298
395   Votes2,698
396   Votes3,476
397   Votes3,047
398   Votes7,422
399   Votes6,093
400   Votes4,162
401  Votes15,372
402   Votes9,588
403   Votes5,165
404   Votes6,054
405   Votes3,154
406   Votes5,183
407   Votes5,509
408   Votes2,558
409   Votes7,927
410   Votes2,947
411  Votes10,230
412   Votes4,280
413   Votes2,671
414  Votes17,577
415   Votes3,569
416   Votes3,131
417   Votes3,609
418   Votes3,047
419   Votes3,891
420   Votes3,571
421   Votes9,920
422   Votes3,938
423   Votes6,777
424  Votes18,161
425   Votes5,438
426   Votes9,535
427   Votes5,639
428   Votes4,864
429   Votes3,923
430   Votes3,596
431   Votes5,417
432   Votes5,195
433   Votes3,726
434   Votes4,860
435  Votes21,442
436   Votes3,424
437   Votes3,255
438   Votes7,196
439   Votes2,650
440   Votes4,540
441   Votes3,045
442   Votes4,456
443   Votes3,462
444   Votes4,130
445   Votes2,840
446   Votes6,958
447   Votes4,771
448   Votes4,832
449   Votes3,934
450   Votes2,569
451   Votes3,513
452   Votes2,863
453   Votes2,968
454   Votes4,018
455   Votes7,141
456   Votes3,630
457   Votes3,454
458   Votes3,569
459   Votes4,304
460   Votes4,860
461   Votes5,346
462   Votes3,950
463   Votes2,670
464  Votes27,603
465   Votes3,297
466   Votes2,657
467  Votes20,608
468   Votes2,640
469   Votes3,701
470   Votes2,565</code></pre>
</div>
</div>
</section>
<section id="question-2." class="level2">
<h2 class="anchored" data-anchor-id="question-2.">Question 2.</h2>
<p>Start web scrapping to create a Data Frame with columns: Title, Year, Duration, Rating, Votes</p>
<p>Ans:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>df_title_names <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">title_names =</span> <span class="fu">unlist</span>(all_title_names))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>df_title_names <span class="ot">&lt;-</span> (<span class="fu">tail</span>(<span class="fu">head</span>(df_title_names,<span class="sc">-</span><span class="dv">1</span>),<span class="sc">-</span><span class="dv">1</span>))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>df_title_names <span class="ot">&lt;-</span> <span class="fu">as.character</span>(df_title_names[[<span class="dv">1</span>]])</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>Titles <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"^</span><span class="sc">\\</span><span class="st">d+</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">s*"</span>, <span class="st">""</span>, df_title_names)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>indices_to_remove <span class="ot">&lt;-</span> <span class="fu">str_detect</span>(Titles, <span class="st">"Recently viewed|Advanced search"</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>Titles <span class="ot">&lt;-</span> Titles[<span class="sc">!</span>indices_to_remove]</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>df_years <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Year =</span> <span class="fu">unlist</span>(all_years))</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>df_years <span class="ot">&lt;-</span> <span class="fu">as.character</span>(df_years[[<span class="dv">1</span>]])</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>Years <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">str_extract</span>(df_years, <span class="st">"</span><span class="sc">\\</span><span class="st">d{4}"</span>))</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>df_durations <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Durations =</span> <span class="fu">unlist</span>(all_durations))</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>df_durations <span class="ot">&lt;-</span> <span class="fu">as.character</span>(df_durations[[<span class="dv">1</span>]])</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>hours <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(df_durations, <span class="st">"</span><span class="sc">\\</span><span class="st">d+h"</span>) <span class="sc">%&gt;%</span> <span class="fu">str_replace</span>(<span class="st">"h"</span>, <span class="st">""</span>) <span class="sc">%&gt;%</span> <span class="fu">as.numeric</span>()</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>hours[<span class="fu">is.na</span>(hours)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>minutes <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(df_durations, <span class="st">"</span><span class="sc">\\</span><span class="st">d+m"</span>) <span class="sc">%&gt;%</span> <span class="fu">str_replace</span>(<span class="st">"m"</span>, <span class="st">""</span>) <span class="sc">%&gt;%</span> <span class="fu">as.numeric</span>()</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>minutes[<span class="fu">is.na</span>(minutes)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>Durations <span class="ot">&lt;-</span> hours <span class="sc">*</span> <span class="dv">60</span> <span class="sc">+</span> minutes</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>df_ratings <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Ratings =</span> <span class="fu">unlist</span>(all_ratings))</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>df_ratings <span class="ot">&lt;-</span> <span class="fu">as.character</span>(df_ratings[[<span class="dv">1</span>]])</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>Ratings <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"^(</span><span class="sc">\\</span><span class="st">d+</span><span class="sc">\\</span><span class="st">.?</span><span class="sc">\\</span><span class="st">d*).*"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1"</span>, df_ratings))</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>df_votes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Votes =</span> <span class="fu">unlist</span>(all_votes))</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>df_votes<span class="ot">&lt;-</span><span class="fu">as.character</span>(df_votes[[<span class="dv">1</span>]])</span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>Votes <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">D"</span>, <span class="st">""</span>, df_votes))</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a><span class="do">### Creating a dataframe###</span></span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a>movie_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Title=</span>Titles, <span class="at">Year=</span>Years , <span class="at">Duration=</span>Durations , <span class="at">Rating=</span>Ratings, <span class="at">Vote=</span>Votes)</span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>movie_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                           Title Year Duration Rating   Vote
1                          Nefes: Vatan Sagolsun 2009      128    8.0  35024
2                                 Babam ve Oglum 2005      108    8.2  91040
3                                      Masumiyet 1997      110    8.1  19298
4                                          Kader 2006      103    7.8  16267
5                                           Uzak 2002      110    7.5  22374
6                                         Eskiya 1996      128    8.1  71705
7                                        A.R.O.G 2008      127    7.3  44635
8                                  Sevmek Zamani 1965       86    8.0   7133
9                                 Hababam Sinifi 1975       87    9.2  42513
10                                     Üç Maymun 2008      109    7.3  22667
11                                         Barda 2007       92    7.0  14685
12                                      G.O.R.A. 2004      127    8.0  66033
13                                      Kabadayi 2007      140    7.8  23635
14                                         Yazgi 2001      119    7.5   6718
15                                    Issiz Adam 2008      113    6.8  22340
16                          Kurtlar Vadisi: Irak 2006      122    5.7  18253
17                                           Yol 1982      107    8.0  14307
18                                    Yahsi Bati 2009      112    7.4  37785
19                                         D@bbe 2006      110    4.4   4734
20                                      Iklimler 2006       97    7.1  14007
21                                     Vizontele 2001      110    8.0  38405
22                      Her Sey Çok Güzel Olacak 1998      107    8.1  27122
23                                        Pardon 2005       99    8.1  22669
24                         Dünyayi Kurtaran Adam 1982       91    4.4   8014
25                                    Tosun Pasa 1976       90    8.9  24329
26                                 Bekleme Odasi 2003       92    6.3   3166
27                                    Agir Roman 1997      120    7.6  11725
28                              Tabutta Rövasata 1996       75    7.7  10854
29                                Organize Isler 2005      106    7.4  35029
30                                        Gemide 1998      102    7.9  15724
31                      Selvi Boylum Al Yazmalim 1977       90    8.5  16724
32                                        Itiraf 2001      100    7.0   3923
33                 Dünyayi Kurtaran Adam'in Oglu 2006      110    1.5  16706
34                                  Üçüncü Sayfa 1999       92    7.3   4265
35                              Neredesin Firuze 2004      128    7.4  12406
36                              Saban Oglu Saban 1977       90    8.7  18534
37                               Mayis Sikintisi 1999      130    7.3   6629
38                Deli Yürek: Bumerang Cehennemi 2001      123    6.5   4121
39                                     Kolpaçino 2009       98    6.5  13656
40                                     Susuz Yaz 1963       90    7.8   5494
41                                  Recep Ivedik 2008       90    4.8  28355
42                                  Günesin Oglu 2008       89    7.0   6060
43                                        Kasaba 1997       85    7.0   6426
44                                       D@bbe 2 2009       85    3.0   2661
45                                         Sinav 2006      120    6.6  11254
46                                 Günesi Gördüm 2009      120    6.6  10575
47                                Çöpçüler Krali 1977       80    8.5  21181
48                                       Yumurta 2007       97    6.6   5596
49                               Baska Dilde Ask 2009       98    7.3   7087
50                                     Kiskanmak 2009       96    6.5   3464
51    Muro: Nalet Olsun Içimdeki Insan Sevgisine 2008       90    3.9   3211
52                                        Vavien 2009      100    7.5  13504
53                                Recep Ivedik 2 2009      107    4.5  22333
54                                        C Blok 1994       92    6.1   3374
55                                  Gönül Yarasi 2005      142    7.8  10406
56                        Kurtlar Vadisi: Gladio 2009       97    6.2   5288
57                                 Aaahh Belinda 1986      100    7.8   3498
58                                      Hokkabaz 2006      122    7.4  34181
59                                    Zügürt Aga 1985      101    8.7  16137
60                                      Sonbahar 2008       99    7.7   6741
61                                    Üç Kagitçi 1981       88    7.7   6089
62                                    Muhsin Bey 1987      119    8.4  11522
63                                Anlat Istanbul 2005       99    7.3   6865
64                                         Duvar 1983      117    8.0   4383
65                               Merakli Köfteci 1976       75    7.2   4199
66                                        Salako 1974       87    7.4   6438
67                              Çarikli Milyoner 1983       86    6.7   3314
68              Karpuz Kabugundan Gemiler Yapmak 2004       97    7.8   6466
69                                 Neseli Günler 1978       95    8.7  11807
70                                 Anayurt Oteli 1987      101    7.5   4444
71                                         Zübük 1980       88    8.5  10565
72                                        Kosmos 2009      122    7.1   5130
73                                 Süt Kardesler 1976       80    8.8  20889
74                                           120 2008      114    7.2   7031
75                                   Kibar Feyzo 1978       83    8.7  17126
76                                          Sürü 1978      117    8.2   5259
77                                           Gen 2006      105    4.2   3640
78                               7 Kocali Hürmüz 2009      122    6.3   5818
79                                  Kahpe Bizans 1999       97    5.9   7513
80                                En Büyük Saban 1984       93    6.7   3026
81                                    Propaganda 1999      120    7.1  10029
82                                      Mutluluk 2007      105    7.5   7798
83                                   Gölge Oyunu 1993      103    7.7   3721
84                                 Tatar Ramazan 1990       95    7.9   3387
85                                   Beynelmilel 2006      106    7.2   8141
86                                Çilgin Dersane 2007      100    1.9   3899
87                                     Yazi Tura 2004      102    7.6   6495
88                              Devrim Arabalari 2008      120    8.0  12609
89                  Hababam Sinifi Sinifta Kaldi 1975       95    8.9  24369
90                                  Tatli Dillim 1972       94    7.1   2805
91                                Vesikali Yarim 1968       89    7.9   3249
92                               Kutsal Damacana 2007      105    5.1   9842
93                                 Sari Mercedes 1993       90    7.8   3207
94                                  Egreti Gelin 2005      115    6.2   3141
95                                Canim Kardesim 1973       85    8.6  10097
96                   Dar Alanda Kisa Paslasmalar 2000      120    7.3   3275
97                       Mustafa Hakkinda Hersey 2004      119    7.5   9741
98                                      Musallat 2007       95    5.9   4350
99                                   Güz Sancisi 2009      112    6.1   2555
100                                Küçük Kiyamet 2006       90    6.3   2628
101             Hacivat Karagöz Neden Öldürüldü? 2006      135    7.5  13079
102                                  Beyaz Melek 2007      115    6.5   7339
103                                         Umut 1970      100    8.0   4245
104                        Uçurtmayi Vurmasinlar 1989       85    8.3   7078
105                              Vizontele Tuuba 2003      111    6.5  16375
106                              Korkusuz Korkak 1979       77    8.1   7222
107                                    Ah Nerede 1975       90    7.6   4761
108                                      Tokatçi 1983       83    7.7   6177
109              Maskeli Besler: Intikam Pesinde 2005       89    4.4   6059
110                   Azize: Bir Laleli Hikayesi 1999       85    6.9   3644
111                                          Süt 2008      102    6.6   3317
112                                 Neseli Hayat 2009      100    6.1   7525
113                       Hababam Sinifi Tatilde 1977       97    8.6  18636
114                                       Insaat 2003      113    7.2   4025
115                                      Arabesk 1989       92    8.0   8302
116                          Köyden Indim Sehire 1974       91    8.3  11647
117                Istanbul Kanatlarimin Altinda 1996      119    7.0   3821
118                                  Aile Serefi 1976       95    8.0   3792
119                         Maskeli Besler: Irak 2007      104    3.8   5257
120                                      Mustafa 2008      130    6.7   2844
121          Ask Filmlerinin Unutulmaz Yönetmeni 1990      106    7.6   4243
122                    Turist Ömer Uzay Yolu'nda 1973       72    7.2   3636
123                                         Okul 2004      100    4.1   3632
124                                  Mavi Boncuk 1975       76    7.8   9553
125                                  Banker Bilo 1980       85    7.6   7352
126                                         Büyü 2004       95    3.0   3920
127                                    Bes Vakit 2006      111    7.3   4372
128                                        Semum 2008      116    5.0   4027
129                   Keloglan Karaprens'e Karsi 2006      105    1.6   9616
130                              Çiplak Vatandas 1985       74    7.5   4936
131                               O... Çocuklari 2008      120    6.4   5446
132                      Hababam Sinifi Uyaniyor 1976       94    8.7  20640
133                                  Çiçek Abbas 1982       87    8.0  11021
134                              Kapicilar Krali 1976       84    8.4  13359
135                                 Gülen Gözler 1977       97    8.4   7591
136                                    Hayat Var 2008      121    7.3   3432
137                           Pandora'nin Kutusu 2008      112    7.2   2938
138                                        Polis 2007      113    6.6   6235
139                      Hababam Sinifi Üç Buçuk 2005       98    3.0   8696
140                                       Yoksul 1986       77    7.3   3000
141                       Son Osmanli Yandim Ali 2007      126    6.9   6803
142                                   Bizim Aile 1975       92    8.4   7213
143                                  Kanli Nigar 1981       81    7.1   3403
144                                 11'e 10 Kala 2009      110    7.2   2793
145                               Doktor Civanim 1983       87    6.9   4069
146                           Davaro: Son Eskiya 1981       94    8.1   9204
147                                 Kaç Para Kaç 1999      100    7.5   3713
148                                         Vali 2009       93    7.3   4948
149                             Dondurmam Gaymak 2006      100    6.6   6542
150                              Yedi Bela Hüsnü 1983       84    7.7   7477
151                     Hababam Sinifi Güle Güle 1981       81    6.3   6186
152                                  Devlet Kusu 1980       79    6.9   2578
153                                   Gülen Adam 1990       91    6.9   4113
154                                      Fasulye 2000      105    7.2   2602
155                              Korkuyorum Anne 2004      128    7.5   3289
156                                Düttürü Dünya 1988       91    7.3   2999
157                          Beyza'nin Kadinlari 2006      137    6.2   2767
158                                         Araf 2006       97    2.4   4276
159                       Hababam Sinifi Askerde 2005      112    3.3   7787
160                          Osmanli Cumhuriyeti 2008      100    5.2   7220
161                                     Ögretmen 1988       89    7.2   2620
162                             Deli Deli Küpeli 1986       87    7.3   3727
163                                       Davaci 1987       79    7.1   3420
164                                       Sultan 1978       88    7.5   3830
165                                        Garip 1986       96    7.1   4270
166                                  Sakar Sakir 1977       81    8.0   8952
167                               Salak Milyoner 1974       84    7.9   7833
168                       Hababam Sinifi Merhaba 2004      118    3.2   6964
169                                Koltuk Belasi 1990       85    7.0   2633
170                                Salvar Davasi 1983       90    7.1   2712
171                              Filler ve Çimen 2000      115    7.0   2806
172                                Ask Tutulmasi 2008       99    5.5   3019
173                                O Simdi Asker 2003      125    4.9   2742
174                                     Sabaniye 1984       93    6.2   3708
175                          Sans Kapiyi Kirinca 2005      107    6.3   4661
176                                     Varyemez 1991       93    6.6   2820
177               Hababam Sinifi Dokuz Doguruyor 1978       88    7.3   8939
178                                      Kilibik 1983       85    7.0   3468
179                         On the Way to School 2008       81    7.4   3089
180                                    Sekerpare 1983       90    7.9   6746
181                                Sosyete Saban 1985       92    6.9   3528
182                                   Inek Saban 1978       71    7.5   4382
183                            Yüz Numarali Adam 1978       79    7.7   5934
184                                      Postaci 1984       87    7.0   4602
185                                        Hanzo 1975       77    6.3   4367
186                                      Namuslu 1984       93    8.1   7353
187                                       Kiraci 1987       94    6.7   2714
188                              Ortadirek Saban 1984       82    7.2   4955
189                            Katma Deger Saban 1985       85    6.5   4137
190                              Ne Olacak Simdi 1979       83    7.5   3248
191                                         Ulak 2008      109    6.8   4834
192                            Köseyi Dönen Adam 1978       82    7.1   3037
193                                 Gerzek Saban 1980       76    7.1   3139
194                  Son Ders: Ask ve Üniversite 2008       99    6.9   2562
195                     Emret Komutanim: Sah Mat 2007      100    1.5   7047
196                               Komser Sekspir 2000      113    5.8   3433
197                                   Talih Kusu 1989       92    7.0   2902
198                                 Tarzan Rifki 1986       83    6.4   3154
199                                    Gol Krali 1981       81    6.8   3933
200                                 Saskin Damat 1975       78    6.8   2737
201                                  Avanak Apti 1978       86    6.9   4459
202                                    Milyarder 1987       96    7.5   4554
203                                     Oh Olsun 1974       86    7.2   3218
204                                  Hirsiz Var! 2005       96    4.4   3260
205                                    Japon Isi 1987       89    6.1   3783
206                             Selamsiz Bandosu 1988      107    7.7   3905
207                               Gurbetçi Saban 1985       87    6.5   3284
208                           Saban Pabucu Yarim 1985       93    6.4   2973
209                                Dolap Beygiri 1982       90    7.2   2677
210                               Sahte Kabadayi 1976       77    7.6   6252
211                               Bekçiler Krali 1979       82    7.6   6579
212                               Atla Gel Saban 1984       83    7.6   5137
213                                 Uzak Ihtimal 2009       90    7.0   2736
214                               Umudumuz Saban 1979       83    7.1   3582
215                       Maskeli Besler: Kibris 2008       87    3.1   5552
216                      Erkek Güzeli Sefil Bilo 1979       67    6.9   2710
217                                 Sark Bülbülü 1979       89    7.5   4350
218                          Dokunmayin Sabanima 1979       79    7.2   4090
219                                Sen Dul Saban 1986       94    6.5   2711
220                              Iyi Aile Çocugu 1978       79    7.1   3025
221                               Kanal-i-zasyon 2009      113    5.0   3908
222                             Ibo ile Güllüsah 1977       88    6.1   3498
223                            Kuru Otlar Üstüne 2023      197    8.1   5099
224                      Istanbul Için Son Çagri 2023       91    5.3   7408
225                     Yedinci Kogustaki Mucize 2019      132    8.2  54178
226                               Ölümlü Dünya 2 2023      117    7.5   3508
227                                       Bihter 2023      113    3.6   3360
228                                 Ölümlü Dünya 2018      107    7.6  30274
229                                   Kis Uykusu 2014      196    8.0  54651
230                                       Dag II 2016      135    8.2 109871
231                               Do Not Disturb 2023      114    6.3   8785
232                    Ayla: The Daughter of War 2017      125    8.3  42995
233                                 Kurak Günler 2022      129    7.6  11172
234                                  Ahlat Agaci 2018      188    8.0  27020
235                      Bir Zamanlar Anadolu'da 2011      157    7.8  49372
236                          Dabbe: Cin Çarpmasi 2013      134    6.8   7112
237                                       Baskin 2015       97    5.8  12110
238                                         Kedi 2016       79    7.6  15614
239                                  Sen Inandir 2023      104    5.6   2587
240                                       Mucize 2015      136    7.6  13900
241                                   Fort Bliss 2014      116    6.4   3505
242                                       Bergen 2022      145    6.9   5868
243                                    Boga Boga 2023      112    5.7   4481
244                                          Dag 2012       90    7.5  23122
245                           Iyi Adamin 10 Günü 2023      124    6.5   5157
246                                 Cinayet Süsü 2019      112    6.7  19223
247                                   Fetih 1453 2012      165    6.5  58914
248                       The Ottoman Lieutenant 2017      106    6.4  26555
249                                     Limonata 2015      110    7.4  14325
250                             Illegal Hayatlar 2023      105    6.2   4758
251                                Mucize 2: Ask 2019      129    7.2   2785
252                         Kötü Kedi Serafettin 2016       86    7.0   8439
253                                Aaahh Belinda 2023       97    5.3   3089
254                                       Siccîn 2014       96    6.0   5040
255                               Ask Taktikleri 2022       97    5.3   5827
256                                     Can Feda 2018      109    5.5   3655
257                       Insanlar Ikiye Ayrilir 2020      101    6.9   2519
258                                     Tereddüt 2016      105    6.5   2843
259                                      Yeralti 2012      107    7.1  10090
260                        D@bbe: Bir Cin Vakasi 2012      119    5.8   4207
261                       CM101MMXI Fundamentals 2013      139    9.1  46997
262                                Aile Arasinda 2017      124    7.6  25667
263                            Kagittan Hayatlar 2021       96    6.6  13419
264                             Kelebegin Rüyasi 2013      138    7.7  23764
265                          Bizim Için Sampiyon 2018      130    8.2  13032
266                                   Sadece Sen 2014      105    7.3   5938
267                                         Cici 2022      151    7.1   5622
268                              Ikimizin Yerine 2016      126    6.1   7285
269               Cep Herkülü: Naim Süleymanoglu 2019      141    8.2  13655
270                           Kaybedenler Kulübü 2011      105    7.5  25130
271                                     Sarmasik 2015      104    7.9  13134
272                               Yilbasi Gecesi 2022      142    5.8   4416
273                                      Bulanti 2015      112    6.2   2724
274                Organize Isler: Sazan Sarmali 2019      121    6.0  15827
275                                Bursa Bülbülü 2023      120    6.8   6799
276                            Dabbe: Zehr-i Cin 2014      133    5.9   4277
277                                         Daha 2017      115    7.0   4370
278                                   Av Mevsimi 2010      140    7.4  36265
279                                   Kelebekler 2018      117    7.3  15789
280                                   Kar ve Ayi 2022       93    6.6   2589
281                                    Geçen Yaz 2021      101    6.3   3391
282                     Sen Aydinlatirsin Geceyi 2013      107    7.7  10485
283                                       Müslüm 2018      136    7.6  19957
284                                 Aykut Eniste 2019      115    7.0   7412
285                                 Incir Reçeli 2011       94    6.5  14119
286                            Unutursam Fisilda 2014      118    7.5  12922
287                               Recep Ivedik 7 2022      133    5.2   6370
288                                  Pek Yakinda 2014      134    7.3  35457
289                                      Delibal 2015      117    6.7  12124
290                                   Nuh Tepesi 2019      109    7.1   6290
291                        Kurtlar Vadisi: Vatan 2017      105    3.9   3334
292                                 Dügün Dernek 2013      106    6.9  23519
293                                   Su ve Ates 2013      113    6.1   4881
294                                      Azizler 2021       96    6.0  11271
295                                 Biz Böyleyiz 2020      121    5.6   5809
296                                     Siccin 2 2015       93    6.1   3707
297                                     Panzehir 2014      125    6.9   4069
298                                  Okul tirasi 2021       85    7.4   2954
299                               Hedefim Sensin 2018      113    6.2   4995
300                              Mutluluk Zamani 2017      108    5.9   5761
301                            Bir Ask Iki Hayat 2019      106    6.1   3103
302                              Celal ile Ceren 2013      114    3.1  43233
303                                      Deliler 2018      121    5.1   3488
304                             Sen Yasamaya Bak 2022      104    5.7   3726
305                                 Cingöz Recai 2017      113    4.8   4708
306                               Babamin Kemani 2022      112    6.4   4009
307                               Aci Tatli Eksi 2017      100    6.0   2789
308                   Enes Batur Gerçek Kahraman 2019       99    1.4   9516
309                                    Sag Salim 2012       98    6.3   6501
310               Behzat Ç.: Seni Kalbime Gömdüm 2011      110    7.5  10399
311                        Ask Tesadüfleri Sever 2011      118    7.2  19483
312                                       Çiçero 2019      126    6.5   6394
313                               Annemin Yarasi 2016      120    7.3   4132
314                                Kiz Kardesler 2019      108    7.4   4663
315                            Senden Bana Kalan 2015      117    6.5   3400
316                            Ise Yarar Bir Sey 2017      104    7.6   5511
317                       New York'ta Bes Minare 2010      119    5.7  15445
318                             Kolpaçino: Bomba 2011       92    5.8   7949
319                                          Kin 2021      105    5.5   4789
320                     Kaybedenler Kulübü Yolda 2018       96    5.7   2961
321                                Dabbe (Dab6e) 2015      160    5.6   3182
322                       Dügün Dernek 2: Sünnet 2015      112    6.3  11164
323               Cumali Ceber: Allah Seni Alsin 2017      100    1.0  39269
324                               Aykut Eniste 2 2021      115    6.5   3595
325                                        Sibel 2018       95    6.8   2877
326                               Kardesim Benim 2016      120    5.8   5010
327                   Karakomik Filmler: Kaçamak 2019       60    5.5  10470
328                              Asiklar Bayrami 2022      102    5.7   2994
329                                 Itirazim Var 2014      110    7.7  13675
330                             Eltilerin Savasi 2020      118    5.8   5008
331                                 Benim Dünyam 2013      100    7.5   5738
332                                Hadi Be Oglum 2018      112    7.0   3781
333                      Karakomik Filmler: Deli 2020       60    6.5   9140
334                                  Küçük Esnaf 2016      104    5.6   4551
335               Sen Hiç Ates Böcegi Gördün Mü? 2021      113    6.2   5489
336                                   Arif V 216 2018      125    7.0  38570
337                          Kolonya Cumhuriyeti 2017      110    5.8   5368
338                            Cebimdeki Yabanci 2018       95    6.8   9431
339                            Dedemin Insanlari 2011      126    8.0  11218
340                                Yol Arkadasim 2017      115    6.1   7478
341                      Bi Küçük Eylül Meselesi 2014      106    7.1  10860
342                                      Görümce 2016      109    5.0   3472
343                   Sen Kiminle Dans Ediyorsun 2017      106    5.6   2613
344            Fakat Müzeyyen Bu Derin Bir Tutku 2014      106    6.6   3732
345                     Behzat Ç. Ankara Yaniyor 2013       97    7.4   6858
346                                 Tamam miyiz? 2013       92    7.0   5487
347                               Iftarlik Gazoz 2016      115    7.3  15308
348                                 9 Kere Leyla 2020      112    3.7   7870
349               Enes Batur Hayal mi Gerçek mi? 2018      110    2.0  55886
350                                        Selam 2013      104    6.2   2619
351                                 Beni Çok Sev 2021      124    7.0   3095
352                          Zaman Makinesi 1973 2014      105    6.3   3273
353                           Istanbul Kirmizisi 2017      110    5.6   6822
354              Bizans Oyunlari: Geym of Bizans 2016      101    3.7   3196
355                                  Evim Sensin 2012       91    5.0   6095
356                                 Eksi Elmalar 2016      114    7.1   7831
357                    Karakomik Filmler: Emanet 2020       60    5.6   7650
358                                     Iyi Oyun 2018      114    4.5   3961
359                  Çok Filim Hareketler Bunlar 2010      104    4.5   5160
360                             Yarina Tek Bilet 2020       90    5.6   5418
361                                Hükümet Kadin 2013       99    6.5   9181
362                            Çakallarla Dans 6 2022      116    5.3   5265
363                   Karakomik Filmler: 2 Arada 2019       60    6.4  13414
364                               Recep Ivedik 3 2010       95    4.2  20792
365                                  Vay Arkadas 2010      100    6.3   2599
366                            Sevimli Tehlikeli 2015      113    6.0   3849
367                                  Baba Parasi 2020      116    4.6   3539
368                              Bayi Toplantisi 2020      114    4.6   4200
369                            Kocan Kadar Konus 2015      108    6.1   5428
370                                     Deli Ask 2017      104    5.5   3124
371                       Hababam Sinifi Yeniden 2019      106    2.2   3849
372                                         Reis 2017      108    1.0  73974
373                              Ask Sana Benzer 2015      115    3.8   3526
374                                         Veda 2010      114    7.2   7481
375                      Ask Tesadüfleri Sever 2 2020      124    7.1   3211
376                            Türk Isi Dondurma 2019      120    6.4   5221
377                        Ali Baba ve 7 Cüceler 2015      114    5.6  20982
378                                       Abluka 2015      119    7.2   4320
379                               Incir Reçeli 2 2014      103    6.0   4594
380                                         Börü 2018      111    6.7   4652
381                          Siccîn 3: Cürmü Ask 2016      110    6.1   3018
382                               Recep Ivedik 4 2014      117    3.8  18081
383                           Bana Masal Anlatma 2015      103    7.3  16479
384                               Bir Baba Hindu 2016      112    2.6   2632
385                               Eyyvah Eyvah 3 2014      105    5.9   7920
386                                Kaçma Birader 2016      107    6.8   3659
387                             Gözetleme Kulesi 2012       96    7.1   2834
388                           Kurtulus Son Durak 2012      106    6.2   2710
389                               Recep Ivedik 6 2019      110    3.0   8627
390                     Kutsal Damacana 2: Itmen 2010       98    3.0   5455
391                                  Çalgi Çengi 2011       90    7.0  13541
392                         Çanakkale Yolun Sonu 2013      101    7.1   5094
393                                     Deliha 2 2018      106    4.7   2830
394                              Çakallarla Dans 2010      102    5.6   7298
395                             Yolun Açik Olsun 2022      119    6.5   2698
396                      Sag Salim 2: Sil Bastan 2014       98    4.9   3476
397             Çakallarla Dans 3: Sifir Sikinti 2014      102    5.0   3047
398                                          Bal 2010      103    7.1   7422
399                                  Uzun Hikâye 2012      125    7.5   6093
400                       Selam: Bahara Yolculuk 2015      126    7.1   4162
401                               Eyyvah Eyvah 2 2011      106    6.6  15372
402                                    Kara Bela 2015      105    6.7   9588
403                                Sofra Sirlari 2017      103    6.7   5165
404                                     Çogunluk 2010      110    7.4   6054
405                    Sümela'nin Sifresi: Temel 2011       90    3.7   3154
406                              Hükümet Kadin 2 2013      105    6.1   5183
407                                 Ejder Kapani 2010      105    6.5   5509
408                                     Ya Sonra 2011      105    5.2   2558
409                             Ailecek Saskiniz 2018      113    6.1   7927
410                                   Kötü Çocuk 2017      125    2.0   2947
411                               Cumali Ceber 2 2018      100    1.2  10230
412                                   Yol Ayrimi 2017      150    6.7   4280
413                                   Sonsuz Ask 2017      114    6.1   2671
414                               Recep Ivedik 5 2017      114    3.4  17577
415                                Tatlim Tatlim 2017       95    5.6   3569
416                          Güzelligin Portresi 2019      127    6.3   3131
417                                       Kayhan 2018      105    2.2   3609
418                              Kafalar Karisik 2018       95    3.0   3047
419                                 Tepenin Ardi 2012       94    7.2   3891
420            Romantik Komedi 2: Bekarliga Veda 2013      105    5.2   3571
421                                        Müjde 2022       48    1.2   9920
422                                 Dedemin Fisi 2016      100    5.6   3938
423                              Osman Pazarlama 2016      114    3.5   6777
424                                 Bizim Hikaye 2015       97    5.4  18161
425                                  Sen Kimsin? 2012      101    5.0   5438
426                     Kurtlar Vadisi: Filistin 2011      105    6.1   9535
427                           Anadolu Kartallari 2011      120    6.2   5639
428                           Kolpaçino 3. Devre 2016       93    4.1   4864
429                                    Yok Artik 2015       99    5.8   3923
430             Hür Adam: Bediüzzaman Said Nursi 2011      163    4.6   3596
431                             G.D.O. Kara Kedi 2013       97    5.3   5417
432                                    Ay Lav Yu 2010      102    5.5   5195
433                              Yol Arkadasim 2 2018      116    5.9   3726
434                                       Deliha 2014      107    4.6   4860
435                                 Eyyvah Eyvah 2010      104    7.0  21442
436 Celal Tan ve Ailesinin Asiri Acikli Hikayesi 2011       90    6.4   3424
437                                 Ali Kundilli 2015      118    5.4   3255
438                               Berlin Kaplani 2012       98    5.2   7196
439                                  Sabit Kanca 2013      100    3.1   2650
440                                  Gise Memuru 2010       96    6.4   4540
441                            Çakallarla Dans 4 2016      109    4.1   3045
442                                 Olanlar Oldu 2017      108    6.2   4456
443                   Kocan Kadar Konus: Dirilis 2016      108    5.7   3462
444                            Birlesen Gönüller 2014      126    7.5   4130
445                                 Zenne Dancer 2011      104    7.1   2840
446                                  OHA Diyorum 2017       90    1.6   6958
447                                    Borç Harç 2019       90    1.4   4771
448                             Mandira Filozofu 2014      109    6.6   4832
449                                 Nadide Hayat 2015      118    6.3   3934
450                            Çakallarla Dans 5 2018      102    3.8   2569
451                                 Yozgat Blues 2013       93    6.8   3513
452                                 Bizi Hatirla 2018      120    7.4   2863
453                        Sen Benim HerSeyimsin 2016      107    6.2   2968
454                   Bizim Büyük Çaresizligimiz 2011      102    6.8   4018
455                     Patron Mutlu Son Istiyor 2014      109    6.0   7141
456                      Entelköy Efeköy'e Karsi 2011      111    6.6   3630
457                          Niyazi Gül Dörtnala 2015      106    4.5   3454
458                                 Içimdeki Ses 2015       93    5.9   3569
459                                Hadi Insallah 2014       96    5.4   4304
460                           Çalgi Çengi Ikimiz 2017      116    5.6   4860
461                              Romantik Komedi 2010       95    5.3   5346
462           Çakallarla Dans 2: Hastasiyiz Dede 2012      101    4.6   3950
463                                        Açela 2020       70    2.7   2670
464                               Kod Adi K.O.Z. 2015      114    1.7  27603
465                           Resistance Is Life 2017       73    7.7   3297
466                             Alamet-i Kiyamet 2016       88    4.7   2657
467                            15/07 Safak Vakti 2021       95    1.2  20608
468                               Deniz ve Günes 2018       96    4.9   2640
469                Sihirbazlik Okulunda Bir Türk 2015       91    1.7   3701
470                           Guardian of Angels 2018       56    7.2   2565</code></pre>
</div>
</div>
</section>
<section id="question-3." class="level2">
<h2 class="anchored" data-anchor-id="question-3.">Question 3.</h2>
<section id="a" class="level3">
<h3 class="anchored" data-anchor-id="a">3.a</h3>
<p>Arrange your data frame in descending order by Rating. Present the top 5 and bottom 5 movies based on user ratings. Have you watched any of these movies? Do you agree or disagree with their current IMDb Ratings?</p>
<p>Ans: I’m not sure about the first 5 but the last 5 , especially the last movie , I have to admit it’s the worst :)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>top5_movies <span class="ot">&lt;-</span> movie_data <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Ratings)) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>bottom5_movies <span class="ot">&lt;-</span> movie_data <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Ratings)) <span class="sc">%&gt;%</span> <span class="fu">tail</span>(<span class="dv">5</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>top5_movies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         Title Year Duration Rating  Vote
1               Hababam Sinifi 1975       87    9.2 42513
2       CM101MMXI Fundamentals 2013      139    9.1 46997
3                   Tosun Pasa 1976       90    8.9 24329
4 Hababam Sinifi Sinifta Kaldi 1975       95    8.9 24369
5                Süt Kardesler 1976       80    8.8 20889</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>bottom5_movies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                             Title Year Duration Rating  Vote
466                 Cumali Ceber 2 2018      100    1.2 10230
467                          Müjde 2022       48    1.2  9920
468              15/07 Safak Vakti 2021       95    1.2 20608
469 Cumali Ceber: Allah Seni Alsin 2017      100    1.0 39269
470                           Reis 2017      108    1.0 73974</code></pre>
</div>
</div>
</section>
<section id="b" class="level3">
<h3 class="anchored" data-anchor-id="b">3.b</h3>
<p>Check the ratings of 2-3 of your favorite movies. What are their standings?</p>
<p>Ans:</p>
<p>My favorite movies are indicated as “favorite_movies” , you are gonna see my favorite movies ratings , votes and etc.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>favorite_movies <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"A.R.O.G"</span>,<span class="st">"Hababam Sinifi"</span>,<span class="st">"G.O.R.A."</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>favorite_movies_data <span class="ot">&lt;-</span> movie_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Title <span class="sc">%in%</span> favorite_movies)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>favorite_movies_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Title Year Duration Rating  Vote
1        A.R.O.G 2008      127    7.3 44635
2 Hababam Sinifi 1975       87    9.2 42513
3       G.O.R.A. 2004      127    8.0 66033</code></pre>
</div>
</div>
</section>
<section id="c" class="level3">
<h3 class="anchored" data-anchor-id="c">3.c</h3>
<p>Considering that audience rating is a crucial indicator of movie quality, what can you infer about the average ratings of Turkish movies over the years? Calculate yearly rating averages and plot them as a scatter plot. Hint: Use functions like group_by(), summarise(), mean(), ggplot(), geom_point(). Similarly, plot the number of movies over the years. You might observe that using yearly averages could be misleading due to the increasing number of movies each year. As an alternative solution, plot box plots of ratings over the years (each year having a box plot showing statistics about the ratings of movies in that year). What insights do you gather from the box plot?</p>
<p>Ans:</p>
<p>When we looked at the average ratings of Turkish movies over the years, we found some interesting insights. Initially, we calculated the yearly average ratings and plotted them as a scatter plot. However, we noticed that this approach might be misleading due to the increasing number of movies each year.</p>
<p>As an alternative, we opted for box plots to showcase the distribution of ratings over the years. This allowed us to observe the spread, median, and outliers for each year. It became evident that while average ratings provide a general trend, box plots offer a more nuanced view, revealing the variation and concentration of ratings within each year. This approach provides a richer understanding of how ratings are distributed across different years in Turkish cinema.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#3.c</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>movie_data<span class="sc">$</span>Year <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(movie_data<span class="sc">$</span>Year)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 3.c.1. Calculate yearly rating averages</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>average_ratings <span class="ot">&lt;-</span> movie_data <span class="sc">%&gt;%</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">AverageRating =</span> <span class="fu">mean</span>(Rating),</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">NumberOfMovies =</span> <span class="fu">n</span>())</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 3.c.2. Plot yearly rating averages as a scatter plot</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(average_ratings, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> AverageRating, <span class="at">size =</span> NumberOfMovies)) <span class="sc">+</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Yearly Average Ratings of Turkish Movies"</span>,</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Rating"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment-2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3.c.3. Plot the number of movies over the years</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(average_ratings, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> NumberOfMovies)) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Number of Turkish Movies Over the Years"</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of Movies"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment-2_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3.c.4. Plot box plots of ratings over the years</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(movie_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Year), <span class="at">y =</span> Rating)) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Box Plots of Ratings Over the Years"</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Rating"</span>) <span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">70</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment-2_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
<p>3.d</p>
<p>Do you believe there is a relationship between the number of votes a movie received and its rating? Investigate the correlation between Votes and Ratings</p>
<p>Ans:</p>
<p>I have seen that there a function in R called “cor” which indicates correlation between two data sets or vectors . So I have tried that method to see whether they have a correlation or not ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(movie_data<span class="sc">$</span>Vote, movie_data<span class="sc">$</span>Rating)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>correlation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1308912</code></pre>
</div>
</div>
<p>The correlation coefficient can be inside in interval [-1,1] the correlation of close to 1 shows us there is a positive linear correlation between the data sets or getting close to -1 shows us there is a negative linear correlation between the data sets. if it gets close 0 zero we can say that the power of the correlation gets lower. So 0.13 indicates that there is a slight correlation between them.</p>
</section>
</section>
<section id="question-4." class="level2">
<h2 class="anchored" data-anchor-id="question-4.">Question 4.</h2>
<p>Repeat steps 1 and 2 for a different advanced IMDb search. This time, find Turkish movies that are in the top 1000 movies on IMDb. Perform similar scraping to create another DataFrame with only the columns: Title, Year. • Use IMDb's Advanced Title Search interface with The Title Type set to "Movie" only, the Country set to "Turkey" with the option "Search country of origin only" active, and the Awards &amp; Recognation set to "IMDB Top 1000". You should find a total of 11 movies. • Note that you now have a new data frame with Turkish movies in the top 1000, containing only the title and year. Use your initial data frame and an appropriate join operation to fill in the duration, rating, and votes attributes of the new data frame. • Order the 11 movies based on their Rank. Are these the same first high-rated 11 movies in your initial data frame? If yes, does this imply that IMDb uses rankings alone to determine their top 1000 movie list? If not, what does this imply?</p>
<p>Ans:</p>
<ol type="1">
<li><p>I conducted another IMDb search, this time targeting Turkish movies in the top 1000. After some web scraping magic, I ended up with a fresh dataset containing only the titles and years of these highly-rated movies.</p></li>
<li><p>To enrich this dataset, I merged it with our original data, filling in the missing details like duration, rating, and votes.</p></li>
<li><p>Next, I arranged these 11 top-rated Turkish movies based on their IMDb rank. Now, here’s the interesting part: Yes, the list is composed of the same movies as in the initial dataset, indicating that IMDb doesn’t solely rely on rankings to compile their top 1000. While ranking plays a role, other factors like user ratings and votes also contribute, resulting in a mix of familiar high-rated films in the top 1000 list.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#4.Web Scraping</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>imdb_url <span class="ot">&lt;-</span> <span class="st">"https://m.imdb.com/search/title/?title_type=feature&amp;groups=top_1000&amp;country_of_origin=TR"</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>page <span class="ot">&lt;-</span> <span class="fu">read_html</span>(imdb_url)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>titles <span class="ot">&lt;-</span> page <span class="sc">%&gt;%</span> <span class="fu">html_nodes</span>(<span class="st">".ipc-title__text"</span>) <span class="sc">%&gt;%</span> <span class="fu">html_text</span>()</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>indices_to_remove <span class="ot">&lt;-</span> <span class="fu">str_detect</span>(titles, <span class="st">"Recently viewed|Advanced search"</span>)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>titles <span class="ot">&lt;-</span> titles[<span class="sc">!</span>indices_to_remove]</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>titles <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"^</span><span class="sc">\\</span><span class="st">d+</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">s*"</span>, <span class="st">""</span>, titles)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>years <span class="ot">&lt;-</span> page <span class="sc">%&gt;%</span> <span class="fu">html_nodes</span>(<span class="st">".sc-43986a27-7.dBkaPT.dli-title-metadata"</span>) <span class="sc">%&gt;%</span> <span class="fu">html_text</span>() <span class="sc">%&gt;%</span> <span class="fu">str_extract</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">d{4}"</span>)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>imdb_top1000_movies <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Title =</span> titles, <span class="at">Year =</span> <span class="fu">as.numeric</span>(years))</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(imdb_top1000_movies)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       Title Year
1   Yedinci Kogustaki Mucize 2019
2                 Kis Uykusu 2014
3      Nefes: Vatan Sagolsun 2009
4  Ayla: The Daughter of War 2017
5             Babam ve Oglum 2005
6                Ahlat Agaci 2018
7    Bir Zamanlar Anadolu'da 2011
8                     Eskiya 1996
9                   G.O.R.A. 2004
10                 Vizontele 2001
11  Her Sey Çok Güzel Olacak 1998</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#4. Fill The Remaining Information by using previous dataframe</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>result_df <span class="ot">&lt;-</span> <span class="fu">left_join</span>(imdb_top1000_movies, movie_data, <span class="at">by =</span> <span class="st">"Title"</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co">#4. cOmparison of the datas</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>top11_initial <span class="ot">&lt;-</span> result_df <span class="sc">%&gt;%</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Rating)) <span class="sc">%&gt;%</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">11</span>)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the top 11 movies from the new data frame based on IMDb ranking</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>is_equal <span class="ot">&lt;-</span> <span class="fu">all.equal</span>(top11_initial, movie_data)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">is.logical</span>(is_equal) <span class="sc">&amp;&amp;</span> is_equal) {</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">"The top 11 movies are the same in both data frames."</span>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">"The top 11 movies are different in the two data frames."</span>)</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The top 11 movies are different in the two data frames."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare the two data frames</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>top11_movies <span class="ot">&lt;-</span> movie_data <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Ratings)) <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">11</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>top11_movies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Title Year Duration Rating  Vote
1                Hababam Sinifi 1975       87    9.2 42513
2        CM101MMXI Fundamentals 2013      139    9.1 46997
3                    Tosun Pasa 1976       90    8.9 24329
4  Hababam Sinifi Sinifta Kaldi 1975       95    8.9 24369
5                 Süt Kardesler 1976       80    8.8 20889
6              Saban Oglu Saban 1977       90    8.7 18534
7                    Zügürt Aga 1985      101    8.7 16137
8                 Neseli Günler 1978       95    8.7 11807
9                   Kibar Feyzo 1978       83    8.7 17126
10      Hababam Sinifi Uyaniyor 1976       94    8.7 20640
11               Canim Kardesim 1973       85    8.6 10097</code></pre>
</div>
</div></li>
</ol>


</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../assignments/assignment-1.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Assignment 1</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">Hacettepe IE - EMU 430 - Fall 2023</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>